import type { Cond, Effects, Page, Passage, Story } from '../../src/engine/types';

const is = (flag: string, value: string | boolean = true): Cond => ({ flag, is: value });
const not = (cond: Cond): Cond => ({ not: cond });
const all = (...conds: Cond[]): Cond => ({ all: conds });
const ge = (n: number): Cond => ({ flag: 'lead', gte: n });
const le = (n: number): Cond => ({ flag: 'lead', lte: n });
const cost = (n: number): Effects => ({ add: { lead: -n } });

const raw: Page[] = [
  // ── GOON DOCKS: dusk ─────────────────────────────────────────
  {
    id: 'D01',
    title: 'Two Dollars at the Auction',
    era: 'docks',
    time: 'THU OCT 31 · 5:20 PM',
    cast: ['player', 'chunk', 'mouth', 'key'],
    imagePrompt: `Dusk and drizzle on the front steps of a small hillside house in a fishing neighborhood. The player, seen from behind, sits on the steps in the black overcoat and fedora between Chunk (candy bag) and Mouth (plastic vampire fangs in his hand). Chunk holds up a small brass key on a paper tag. A transistor radio sits on the porch rail. Streetlights are just coming on.`,
    text: [
      `Astoria, Oregon, is a town on a steep hillside above the mouth of the Columbia River. Partway down the hill, where the streets get steep and give up on pavement and the fog comes in off the water, is a neighborhood called the Goon Docks. It’s Thursday, October 31st, 1985, Halloween, a little after twenty past five in the evening. The streetlights have just come on. It’s drizzling, the way it nearly always is.`,
      `You’re sitting on the front steps of your house, three doors down from Mikey Walsh’s. You’re fourteen and dressed as a private eye, in a brown fedora and a long black wool overcoat with a worn velvet collar, two sizes too big, with a small flashlight on a lanyard round your neck. You paid two dollars for the coat last week at the county’s auction of confiscated property, where it was in a box marked LOT 12 with a toaster and some old records.`,
      `Chunk is on the step beside you, working through his bag of candy before trick-or-treating has even started. Mouth is on the step below, trying to fit a pair of plastic vampire fangs over his braces. They’re two of Mikey’s oldest friends. Last summer Mikey, Chunk, Mouth and a few others had an adventure that made the newspapers, and ever since, the kids around here have called themselves the Goonies, after the Goon Docks.`,
      `A transistor radio on the porch rail is playing the local station. In the middle of a chorus, the song cuts off.`,
      `“We interrupt this program for a bulletin from the Clatsop County Sheriff’s Office,” says the announcer. “Three prisoners escaped this afternoon from a state transport near Seaside: Mama Fratelli and her sons, Jake and Francis. They are believed to be driving a stolen white laundry van with a blue stripe along the side. Residents are asked to lock their doors. Deputies are posted at roadblocks on the south road until the nine o’clock shift change. Sheriff Pruitt says tonight’s Halloween bonfire on the river flats will go ahead as usual, under guard.”`,
      `Nobody on the steps says anything. Even Chunk stops chewing.`,
      `You know the name. The Fratellis are a family of crooks who ran a counterfeiting ring out of a restaurant on the waterfront road, printing fake money, until last summer, when the Goonies got in their way. The police arrested all three. Everyone assumed that was the end of the Fratellis.`,
      `Chunk is staring at your coat. “Where did you get that?” he asks. “The county auction,” you say. “It was in a box marked LOT 12.” “That auction was the Fratellis’ stuff, you know,” says Chunk. “The county sold everything it took out of that restaurant.”`,
      `You didn’t know. You look down at the coat, and Chunk reaches over and presses the hem. “There’s something hard in there.” He works a thumbnail under a loose stitch, and something drops into his palm.`,
      `It’s a small brass key on a loop of string, old and heavy for its size, green with salt at the edges. A paper tag is tied to the string. It has been stamped in blue ink: *7 · LOW WATER*.`,
      `“That,” says Mouth slowly, taking out his fangs, “did not come from a toaster.”`,
    ],
    choices: [
      { text: `Take the key to Mikey’s attic, where the Goonies meet`, to: 'D03' },
      { text: `Call the police first`, to: 'D02' },
      { text: `Tuck the key away and go trick-or-treating as planned`, to: 'E01' },
    ],
  },
  {
    id: 'D02',
    title: 'Busy Signal',
    era: 'docks',
    cast: ['player', 'chunk', 'mouth'],
    onEnter: { set: { phoned: true }, ...cost(10) },
    imagePrompt: `A cramped house hallway at dusk. The player, seen from behind in the black overcoat and fedora, holds a beige wall phone with a long curly cord to one ear. Chunk and Mouth watch from the doorway with worried faces.`,
    text: [
      `You take the phone in the hallway of your house, with Chunk and Mouth watching from the doorway, and dial the police.`,
      `The line is busy. You try again, and it’s busy again. On the fifth try it rings, and a tired voice picks up. “Astoria Police, Sergeant Olafsen. Make it quick, kid. I’ve had forty prank calls since lunch.”`,
      `You explain about the Fratellis, the coat and the key. Sergeant Olafsen listens to the whole thing. “Sure,” he says. “The Fratellis are in your coat. And I’m the Headless Horseman. Happy Halloween.” The line clicks.`,
      `It took the better part of ten minutes, and all it taught you is that the police won’t take a call about this. Mouth shrugs. “Mikey’s attic,” he says. “Come on.”`,
    ],
    choices: [{ text: `Go to Mikey’s attic`, to: 'D03' }],
  },
  {
    id: 'D03',
    title: 'Headquarters',
    era: 'docks',
    time: 'THU OCT 31 · 5:45 PM',
    cast: ['mikey', 'data', 'chunk', 'mouth', 'player', 'key'],
    imagePrompt: `Mikey’s cluttered attic clubhouse at dusk: a sagging couch, a workbench under a round window, comics and a hand-lettered GOONIES ONLY sign on the door. Mikey sits on the arm of the couch holding the brass key by its tag. Data works at the bench with a soldering iron. Chunk and Mouth have dropped onto the couch. The player stands in the doorway in the black overcoat and fedora.`,
    text: [
      `Mikey’s attic is up two flights of stairs, behind a door with a hand-lettered sign that says GOONIES ONLY. By quarter to six it’s crowded. Mikey Walsh is thirteen, small and stubborn, and the nearest thing the Goonies have to a leader. He’s sitting on the arm of a sagging couch with the radio on, and his inhaler is in his hand, as it always is when he’s worried. Data is at the workbench by the window. He has round glasses and a yellow rain jacket whose pockets bulge with homemade gadgets, and he’s trying to solder something that smells terrible. The radio is repeating the bulletin. Chunk and Mouth come in behind you and drop onto the couch.`,
      {
        if: is('phoned'),
        text: `“We called the police,” you say. “The sergeant thought it was a prank.” Mikey nods. “They never believe us,” he says. “Not till afterwards.”`,
      },
      `You put the key on the workbench, with the auction receipt you’d stuffed in the coat pocket and never read. It lists LOT 12: gentleman’s overcoat, from the property of the late Mr. Fratelli. Mikey picks up the key and turns the tag over. “Papa Fratelli’s old overcoat,” he says. “He died years ago, but Mama kept his things, and she wouldn’t have let that coat go without a reason. Not if there was something sewn into it.”`,
      `“A reason like what?” asks Chunk.`,
      `“Like the plates,” says Mikey. For anyone who wasn’t around last summer, he explains. The Fratellis didn’t only print fake twenty-dollar bills. They made the plates the bills were printed from, flat sheets of engraved copper so fine that nobody could tell the fakes from the real thing. When the police raided the restaurant, the printing press was there but the plates weren’t. Mama never told anyone where they were. “Without the plates, the Fratellis are three people in a van,” he says. “With them, they’re a bank.”`,
      `“And the county sold the coat,” says Data, without looking up from his soldering. “With the key still inside, because nobody knew it was there.”`,
      `Mikey puts the key down. “The county auction keeps a list of who bought what, with names and addresses. Mama’s going to work out that her husband’s coat is gone, and the first thing she’ll do is read that list.” He looks at you. Nobody says what the second thing is.`,
    ],
    choices: [{ text: `Look at the key properly`, to: 'D04' }],
  },
  {
    id: 'D04',
    title: 'What the Key Is',
    era: 'docks',
    time: 'THU OCT 31 · 6:00 PM',
    onEnter: { set: { running: true } },
    cast: ['mikey', 'data', 'chunk', 'mouth', 'key'],
    imagePrompt: `Close on Data holding the brass key and its paper tag under a desk lamp with tweezers and a jeweler’s eyepiece in the attic clubhouse. Behind him on the wall hangs a hand-drawn Halloween bonfire poster. Mikey and Chunk lean in to look.`,
    text: [
      `Data comes over from the workbench, holds the key under his lamp with a pair of tweezers and looks at it through a jeweler’s eyepiece. “It’s marine brass,” he says. “It’s made not to rust in salt air. Nobody uses a key like this on a house door.” He squints at the tag. “Seven. Low water. I don’t know what that means, but whoever wrote it wanted whoever read it to be sure.”`,
      `On the wall by the door is Mouth’s hand-drawn poster for tonight: ASTORIA HALLOWEEN BONFIRE & COSTUME CONTEST. ON THE RIVER FLATS AT THE FOOT OF SEVENTH STREET. FIRE LIT AT LOW TIDE, 9:41 PM. FIREWORKS TO FOLLOW. HOT CIDER! Underneath, in different ink, Mouth has added: BEST COSTUME WINS A PRIZE. THIS MEANS ME.`,
      `Chunk looks at the poster and sighs. “Last year you could cut through the old Seventh Street Pier to get to the flats. Five minutes. Now it’s fenced off since the big storm, and we have to go all the way round by the road.”`,
      `“My dad’s taking us to the bonfire at nine,” says Mikey. “Everyone’s going, the whole neighborhood. With the sheriff and his deputies there, it’s safe. Until then I’m not allowed out of this house, and neither is anyone else. My mom checks on us every ten minutes.” He looks at the key in Data’s tweezers. “Whatever it opens, you’ll have to find it on your own. And you’ll have to find it before they find you. I’d say you’ve got an hour or two.”`,
      `“If you need a gadget,” says Data, “I’ve got a few. Come by the workbench before you go.”`,
      `“And if you need somebody who knows drains,” says Chunk, “Sloth’s in our garage. He lives with us now. He’s Mama Fratelli’s youngest son, only he’s nothing like her. The Fratellis kept him hidden in their basement for years, and nobody knew he existed until last summer, when we found him. He’s huge and gentle, and he loves chocolate. He used to sneak out of that basement through the drains when nobody was looking, and he still knows every one between here and the river.”`,
      `At six, Mikey’s mother calls up the stairs: Chunk’s and Mouth’s mothers have both phoned, and they’re wanted home for dinner. They leave, and the attic goes quiet. Mikey hands you the key. “Be careful,” he says. You put it in the inside pocket of your overcoat, button the coat to the chin and head out into the drizzle.`,
    ],
    choices: [{ text: `Head down the hill`, to: 'D05' }],
  },
  {
    id: 'D05',
    title: 'The Plan',
    era: 'docks',
    time: 'THU OCT 31 · EVENING',
    cast: ['player'],
    imagePrompt: `Night at the bottom of a hillside street. The player, seen from behind in the black overcoat and fedora, stands at a wide concrete storm-drain arch with an open barred gate, torch in hand, mist and drizzle in the lamplight. Far up the hill, one attic window glows. Alone (nobody else is here).`,
    text: [
      `The head of the Lowline is a concrete arch at the bottom of your street, where the Goon Docks’ big storm drain begins. It runs under the town and down the hill to the river, and every Goon Docks kid knows it comes out under the old Seventh Street Pier. The barred gate across the arch hangs open on one hinge. Up the hill, the light in Mikey’s attic window is still on. It’s fully dark now, and the drizzle has thinned to mist.`,
      `The key is in the inside pocket of your overcoat, against your ribs.`,
      { if: is('hasRope'), text: `Data’s rope launcher hangs from your shoulder: a flattened coffee can with a spring and a hook in it, and thirty feet of braided line.` },
      { if: is('hasMap'), text: `Mrs. Tilden’s photocopied chart of the old waterfront is folded in your pocket.` },
      { if: is('slothPlan'), text: `Sloth is going to wait for you at the heavy iron grate, halfway down the drain.` },
      `By your reckoning, the Fratellis are about {{clock}} behind you. That’s all the head start you have, and every stop between here and the place the key belongs will use some of it.`,
    ],
    choices: [
      { text: `Borrow something from Data’s workbench`, to: 'D06', if: not(is('hasRope')) },
      { text: `Ask Chunk whether Sloth can help`, to: 'D07', if: not(is('visitedSloth')) },
      { text: `Try the library, which stays open late for Halloween story hour`, to: 'T01', if: not(is('hasMap')) },
      { text: `Take the key to the police station on Duane Street`, to: 'T04', if: not(is('visitedPolice')) },
      { text: `Check the lockers at the bus depot`, to: 'T05', if: not(is('visitedDepot')) },
      { text: `Look in at the Fratellis’ old hideout, a boarded-up restaurant on the waterfront road`, to: 'T06', if: not(is('visitedHideout')) },
      { text: `Climb down the Lowline drain to the Seventh Street Pier`, to: 'U01' },
      { text: `Walk along Marine Drive to the Seventh Street Pier`, to: 'T08' },
    ],
  },
  {
    id: 'D06',
    title: 'Data’s Workbench',
    era: 'docks',
    cast: ['data', 'mikey', 'player'],
    onEnter: { set: { hasRope: true }, ...cost(10) },
    imagePrompt: `The attic clubhouse. Data, pushing up his round glasses, loops a coil of braided line with a flattened coffee-can launcher over the shoulder of the player, who is seen from behind in the black overcoat and fedora. Mikey keeps watch at the round window.`,
    text: [
      `You jog back up the hill and climb the attic stairs two at a time. Mikey is at the window, keeping watch. Data is still at the workbench with his soldering iron, and he looks up as if he’s been expecting you.`,
      `“Hold still,” says Data. He loops a coil of braided line over your shoulder, with a flattened coffee can on the end of it. A spring and a steel hook are packed inside. “The Hook-a-Matic, Mark Three. Pull the cord and it fires the hook up to thirty feet. It’ll catch a rafter, a pipe, a ledge. Do not point it at people.” He thinks. “Or lamps. The Mark Two had a problem with lamps.”`,
      `“It’s for climbing,” says Mikey, without turning from the window.`,
      `You thank them and run back down the hill to the head of the Lowline. The trip has cost you some of your lead.`,
    ],
    choices: [{ text: `Go back to the head of the Lowline`, to: 'D05' }],
  },
  {
    id: 'D07',
    title: 'Chunk’s Garage',
    era: 'docks',
    cast: ['chunk', 'sloth', 'player'],
    onEnter: { set: { visitedSloth: true }, ...cost(10) },
    imagePrompt: `A cozy converted garage room at night with a lamp and a too-small bed. Sloth, huge, with shaggy dark hair and one drooping eyelid, sits on the edge of the bed with his big hands knotted. Chunk stands beside him holding a plate of leftovers. The player, seen from behind in the black overcoat and fedora, stands in the doorway.`,
    text: [
      `Chunk’s family lives in a tall, crooked house six streets over, with a detached garage at the back that has been turned into a bedroom. By the time you get there, Chunk is already outside in the drizzle with a plate of leftovers, waiting.`,
      `“He heard the radio,” says Chunk quietly. “He hasn’t eaten.”`,
      `Sloth is sitting on the edge of a bed that’s too small for him, with his huge hands knotted together. He’s the biggest person you’ve ever seen, with shaggy dark hair, one drooping eyelid, and a crooked, hopeful smile that isn’t there at the moment. When he sees you, he lifts a hand a few inches and puts it down again.`,
      `You tell him about the key. At the word “Mama” he flinches, and then he stands up so fast the bed slides backward. “Mama,” he says. “Mama bad. Sloth help.”`,
      `“He knows the drains better than anyone,” says Chunk. “There’s a hatch behind this garage that goes down to the Lowline. He found it his first week here. You can’t take him through the streets. The Fratellis know him by sight, and the streets are the first place they’ll look. But down in the drain, he could meet you, and nobody would ever see him.”`,
      `Sloth nods hard.`,
    ],
    choices: [
      { text: `Ask Sloth to meet you in the drain`, to: 'D08' },
      { text: `Tell him to stay here, safe with Chunk’s family, and go back to the Lowline`, to: 'D05' },
    ],
  },
  {
    id: 'D08',
    title: 'Sloth’s Answer',
    era: 'docks',
    cast: ['sloth', 'chunk', 'player'],
    onEnter: { set: { slothPlan: true } },
    imagePrompt: `The same garage room. Sloth holds both huge hands up as if lifting a heavy bar, grinning. Chunk presses a chocolate bar into the hand of the player, who is seen from behind in the black overcoat and fedora.`,
    text: [
      `You ask Sloth where he’ll meet you.`,
      `Sloth thinks for a long time. Then he holds up one huge hand, palm out, like a wall. “Grate,” he says. “Heavy. Halfway.” He makes the shape of a very big iron bar with his hands, and then he lifts it, and his face lights up. “Sloth lift.”`,
      `“He means there’s a heavy iron grate across the drain, about halfway to the river,” says Chunk. “It’s too heavy for anyone else. He’s been past it. He says there’s water before it too, deep and cold.” Sloth wiggles his fingers like water, then shivers theatrically.`,
      `“I’ll see you there,” you tell him. Sloth shakes your hand, and yours disappears. “Sloth be there,” he says.`,
      `“When Sloth says he’ll be somewhere,” says Chunk, “he’s there.” He digs in his candy bag and presses a chocolate bar into your hand. “For Sloth. In case.”`,
      `You put the chocolate in your pocket and run back down the hill to the Lowline.`,
    ],
    choices: [{ text: `Go back to the head of the Lowline`, to: 'D05' }],
  },

  // ── DOWNTOWN ─────────────────────────────────────────────────
  {
    id: 'T01',
    title: 'The Library',
    era: 'town',
    cast: ['player'],
    onEnter: { set: { hasMap: true }, ...cost(10) },
    imagePrompt: `Inside a small town library at night. A librarian in a pointed witch hat holds the brass key and its paper tag under a desk lamp. The player, seen from behind in the black overcoat and fedora, leans on the desk. In the background, small children in costumes sit on a carpet around a book. Alone with the librarian (no Goonies here).`,
    text: [
      `Astoria’s public library is a squat brick building on a hill, and tonight it’s open until seven for Halloween story hour. When you push through the door, a circle of small children in witch hats and skeleton costumes is sitting on the carpet while a woman in a pointed hat reads aloud from a book about a haunted lighthouse. She’s Mrs. Tilden, the librarian. She taught you how to use the card catalog, and she’s never once let you leave without something to read.`,
      `You wait for the story to end. Then you show her the key and tell her all of it, as quietly as you can. Mrs. Tilden doesn’t laugh. She takes the key in both hands, holds the tag under the desk lamp and says, “Oh, my.”`,
      `“This is an ice-house key,” she says. “Back when the fishermen kept their catch packed in ice, the canneries cut little storerooms into the footings of the piers, below the waterline, so they stayed cold. They were only dry when the tide went out. Fishermen rented numbered lockers in them.” She goes to a flat drawer, pulls out an old harbor chart and runs it through the photocopier. “Locker seven. And the only ice house still standing is the one under the Seventh Street Pier. Look: the door is here, in the east footing.” She taps the copy, folds it and presses it into your hand.`,
      `Then she picks up the phone on her desk. “Someone ought to tell the sheriff’s office about this.” She dials, listens and frowns. “Busy.” She tries again and gets an answering service, and leaves a message. “They say they’ll send someone after the nine o’clock shift change,” she tells you. “Wait here, dear. I’ll make you some cocoa.”`,
      `You thank her, but you don’t have time for cocoa. You’re halfway to the door when a white van pulls up at the curb outside.`,
    ],
    choices: [{ text: `Step outside`, to: 'T02' }],
  },
  {
    id: 'T02',
    title: 'The Library Steps',
    era: 'town',
    cast: ['player', 'deputy'],
    imagePrompt: `Night on wet library steps under one streetlamp. A man in a tan deputy’s uniform, a star badge, a broad-brimmed hat pulled low and a slightly crooked fake mustache holds out a gloved hand toward the player, who is seen from behind in the black overcoat and fedora. At the curb behind him a white laundry van with a blue stripe idles with its window open.`,
    text: [
      `The library steps are wet with drizzle and lit by a single streetlamp. A white van has pulled up at the curb with its engine running. It has a blue stripe along the side and SUDSY’S LAUNDRY painted on the door. Through the open driver’s window you can hear a radio crackling with police calls.`,
      `A man gets out. He’s wearing a tan deputy’s uniform with a star on the chest, a broad-brimmed hat pulled low, and a thick mustache that looks as though it was put on in a hurry. He climbs the steps two at a time.`,
      `“Evening,” he says. “Deputy Dunmore, Sheriff’s Office. Mrs. Tilden called us about a kid with a key. That would be you.” He holds out a gloved hand. “I’ll take that, kid. It’s evidence now. We’ll get it to the station.”`,
    ],
    choices: [
      { text: `Hand him the key`, to: 'E02' },
      { text: `Tell him you’ll take it to the station yourself`, to: 'T03' },
      { text: `Slip back through the library and out the side door, then double back to the Lowline`, to: 'D05' },
    ],
  },
  {
    id: 'T03',
    title: 'The Alley',
    era: 'town',
    cast: ['player', 'deputy'],
    onEnter: cost(15),
    imagePrompt: `A comic chase on a wet downtown street at night. The player, seen from behind in the black overcoat and fedora, ducks among a crowd of tiny trick-or-treaters in skeleton and Frankenstein costumes. Behind them the fake deputy, with his mustache hanging loose, is tangled with a toddler in a pumpkin costume.`,
    text: [
      `“I’ll take it myself,” you say. “Thanks.”`,
      `The deputy’s smile gets wider, and not in a friendly way. “That’s not how it works,” he says, and grabs your arm. His mustache comes loose at one corner. Under the hat, the face is thin, flushed and furious, and you’ve seen it in last summer’s newspapers: Francis Fratelli, Jake’s younger brother.`,
      `You twist out of his grip and run, down the steps, along the side of the library and into an alley that smells of wet cardboard. Francis pounds after you, shouting. You come out onto Commercial Street into a parade of trick-or-treaters: a dozen small skeletons holding hands, a very short Frankenstein, a toddler dressed as a pumpkin. You duck among them. Francis plows straight into the pumpkin, and by the time he has untangled himself and been shouted at by its parents, you’re three blocks away.`,
      `Panting, you cut up through back streets and over fences toward the Goon Docks, and you don’t slow down until you can see the arch of the Lowline again. That was close. Your lead is down to {{clock}}.`,
    ],
    choices: [{ text: `Go to the head of the Lowline`, to: 'D05' }],
  },
  {
    id: 'T04',
    title: 'Duane Street',
    era: 'town',
    cast: ['player'],
    onEnter: { set: { visitedPolice: true }, ...cost(10) },
    imagePrompt: `A bright, cluttered police station front office at night with jack-o’-lanterns on the counter. A heavy, harried desk sergeant with a phone receiver in each hand holds up a small brass key to the light. The player, seen from behind in the black overcoat and fedora, stands at the counter.`,
    text: [
      `The police station on Duane Street is a flat concrete building with jack-o’-lanterns lined up along the front steps and every window lit. Inside, the front office is a mess of ringing phones. Behind the counter, a heavy, harassed desk sergeant has a receiver in each hand and a third phone ringing under a stack of papers. The nameplate says OLAFSEN.`,
      {
        if: is('phoned'),
        text: `“I called earlier,” you say. “About the Fratellis.” Sergeant Olafsen looks up. “The Headless Horseman,” he says. He sighs. “All right, kid. Go on.”`,
        else: `He puts down one receiver, glares at the other and says, “Make it quick.”`,
      },
      `You tell him about the Fratellis, the coat and the key. He stops to look at it. He turns the key over twice. “Marine,” he says. “Never seen one like it.” He rubs his eyes. “Look, here’s how it is. Every deputy’s on a roadblock until the nine o’clock shift change, and then half the department goes down to the flats for the bonfire, same as every year. Nobody can go out to wherever this belongs before then. But I can put it in an evidence envelope and lock it in the drawer, and Monday morning somebody will look at it properly.”`,
    ],
    choices: [
      { text: `Leave the key with him as evidence`, to: 'E03' },
      { text: `Thank him, keep the key and walk back to the Goon Docks`, to: 'D05' },
    ],
  },
  {
    id: 'T05',
    title: 'The Bus Depot',
    era: 'town',
    cast: ['player', 'key'],
    onEnter: { set: { visitedDepot: true }, ...cost(15) },
    imagePrompt: `A long, cold bus depot at night with plastic benches, a ticket window and a wall of numbered coin lockers. The player, seen from behind in the black overcoat and fedora, holds the brass key up to locker number 7, which is clearly the wrong size. A sleepy clerk in a puffy jacket watches from the ticket window. A sailor and two nuns sit on the benches.`,
    text: [
      `The Astoria bus depot is a long, cold room with plastic benches, a ticket window and a wall of coin lockers, each with a number stamped on the door. At this hour there are four people in it: two nuns, a sailor and a man asleep under a newspaper. You find locker 7 at eye level and try the key.`,
      `It doesn’t even go in. The brass barrel is too thick and the teeth are the wrong shape. You try lockers 17, 27 and 70 in case it’s a different kind of seven. Nothing.`,
      `At the ticket window, the clerk, in a puffy jacket, looks at the key through his reading glasses. “That’s not a bus-depot key,” he says. “That’s a boat key. Salt-proof brass.” He hands it back. “Doesn’t fit anything in this building.”`,
      `You walk back to the Goon Docks with your hands in your pockets. The trip has left you with a lead of {{clock}}.`,
    ],
    choices: [{ text: `Go back to the head of the Lowline`, to: 'D05' }],
  },
  {
    id: 'T06',
    title: 'The Old Hideout',
    era: 'town',
    cast: ['player', 'jake', 'francis'],
    onEnter: { set: { visitedHideout: true }, ...cost(15) },
    imagePrompt: `A boarded-up restaurant on a waterfront road at night, peeling red letters over the door. Through a gap between two boards, Jake and Francis Fratelli load green gas cylinders and a metal case into a white laundry van with a blue stripe that is backed into the dining room. The player, seen from behind in the black overcoat and fedora, peers through the gap.`,
    text: [
      `The Fratellis’ old restaurant stands on the waterfront road at the edge of the harbor, boarded up since last summer. The sign over the door still says FRATELLI’S in peeling red letters. You tell yourself the Fratellis won’t be here. It’s the first place the police would look for them.`,
      `Then you see a thin line of light between two boards. You creep up to it and look.`,
      `Inside, in what used to be the dining room, Jake and Francis Fratelli are carrying equipment out to a white laundry van with a blue stripe, backed up to the kitchen door. Jake is the older brother, a burly man in a battered leather jacket, with a heavy brow and a scowl to match. Francis is thin and wears a loud checked sport coat, and he’s arguing with him. They’re lifting two green gas cylinders and a metal case labeled CUTTING TORCH.`,
      `“If we don’t find the kid with the coat,” says Jake, “we do it the hard way. Mama says the noise won’t matter if there’s enough going on.”`,
      `“Mama says, Mama says,” Francis mutters. “Did she say where the kid is?”`,
      `You step back, and a board creaks. Jake’s head turns. “Hey!” he shouts. “Hey, you in the coat!”`,
      `You run. Jake is much faster than he looks, and you hear Francis crashing through the kitchen behind him. Around the back of the building, between a dumpster and a stack of crates, an iron hatch stands open in the ground with a ladder going down into the dark.`,
      `You don’t have time to think about it. You grab the ladder and go down it.`,
    ],
    choices: [{ text: `Climb down the hatch`, to: 'T07' }],
  },
  {
    id: 'T07',
    title: 'The Cellar Hatch',
    era: 'under',
    cast: ['player'],
    imagePrompt: `Inside an old brick tunnel, low and narrow, with a trickle of water down the middle. The player, seen from behind in the black overcoat and fedora, shines a flashlight along the passage. A square of dim light and an iron hatch are just visible high behind them. Alone (nobody follows).`,
    text: [
      `You pull the hatch shut over your head, climb down the rest of the ladder in the dark and drop into ankle-deep water. Above you, boots hammer on the iron. “It’s a hole!” Francis yells. “The kid went down a hole!”`,
      `“So go after him!” Jake roars.`,
      `There’s a long pause. “I’m not fitting in that,” says Francis. Jake, who’s twice his width, doesn’t argue. The hatch rattles. Nobody opens it.`,
      `You switch on your flashlight. You’re in an old brick tunnel, low and narrow, with a trickle of water down the middle. It’s one of the passages smugglers dug under downtown a century ago, which every kid in Astoria has heard about and none of them has seen. It slopes downhill. You follow it, and after a few hundred yards it opens into a concrete pipe and meets a bigger tunnel at a junction.`,
    ],
    choices: [{ text: `Go on to the junction`, to: 'U02' }],
  },
  {
    id: 'T08',
    title: 'Marine Drive',
    era: 'town',
    cast: ['player', 'francis'],
    onEnter: cost(20),
    imagePrompt: `Misty night on a waterfront road. A huge pile of pallets and driftwood stands on wet river flats beside a long weathered pier with a chain-link gate and a CLOSED sign. A thin man in a loud checked sport coat sits on a crate by the gate with a flashlight. The player, seen from behind in the black overcoat and fedora, watches from the shadow of a boatyard fence.`,
    text: [
      `You decide to walk. Marine Drive runs along the waterfront at the bottom of town, past warehouses and cannery buildings with their windows dark. There are trick-or-treaters on the sidewalks in the mist, and someone’s radio playing in a window, and the river somewhere off to your left, black and wide and smelling of salt.`,
      `At the foot of Seventh Street the road reaches the river flats, a long, wet stretch of sand and mud that stays under water until the tide drops. A huge pile of pallets and driftwood stands on the flats, waiting for tonight’s bonfire. Next to it, the Seventh Street Pier runs out into the dark: a long, weathered wooden pier on pilings, with a chain-link gate across its entrance and a sign that says CLOSED. NO TRESPASSING.`,
      `Somebody is sitting on an upturned crate by the gate with a flashlight: a thin man in a loud checked sport coat, glowering at the passing trick-or-treaters. You’d know him anywhere from last summer’s newspapers. It’s Francis Fratelli, Jake’s younger brother.`,
      `The gate is chained, and he’s watching it. Next door is a boatyard, a yard of upturned boats and a rusty crane behind a low fence, which runs right down to the water beside the pier.`,
    ],
    choices: [
      { text: `Slip through the boatyard next door`, to: 'T09' },
      { text: `Walk up to the gate in your costume like any other trick-or-treater`, to: 'E05' },
    ],
  },
  {
    id: 'T09',
    title: 'The Boatyard',
    era: 'town',
    cast: ['player'],
    onEnter: cost(15),
    imagePrompt: `A boatyard at night with rows of upturned boats on wooden stands and a rusty crane. The player, seen from behind in the black overcoat and fedora, crouches under a hull as a flashlight beam sweeps past. In the background a concrete slipway runs down beside a pier, with a rusty iron ladder dropping into darkness. Alone.`,
    text: [
      `You wait until a gang of trick-or-treaters passes and then climb the low fence into the boatyard. Rows of boats sit propped on wooden stands, hulls dripping. You go from shadow to shadow between them, with Francis’s flashlight beam sweeping the yard every minute or so. Twice you freeze under a hull while it passes.`,
      `At the far end, a concrete slipway runs down to the water beside the pier. Under the pier’s edge, a rusty iron ladder runs from the deck down past the slipway into darkness. You wait for the beam to turn away, then run down the slipway, grab the ladder and climb down it, hand under hand, into the black space below the planks.`,
      `Your feet find a narrow wooden catwalk. Above you, the pier’s planks creak, and somewhere up there a flashlight beam hunts back and forth through the gaps.`,
    ],
    choices: [{ text: `Get your bearings`, to: 'P01' }],
  },

  // ── UNDERGROUND ──────────────────────────────────────────────
  {
    id: 'U01',
    title: 'Down the Lowline',
    era: 'under',
    cast: ['player'],
    onEnter: cost(10),
    imagePrompt: `Inside a wide round concrete storm drain with ribbed walls and a stream of water along the floor. The player, seen from behind in the black overcoat and fedora, walks away down the tunnel with a flashlight beam picking out ripples. Far behind, the arch of the entrance is a dim coin of light. Alone.`,
    text: [
      `You climb through the open gate and down into the Lowline. The tunnel is wide enough for you to stand in, round and ribbed, with a stream of cold water running along its floor and a smell of wet stone. Your flashlight picks out ripples and the occasional empty can. Behind you, the arch shrinks to a coin of dim light, and then to nothing.`,
      { if: is('slothPlan'), text: `Somewhere ahead, halfway down, Sloth will be waiting at the heavy iron grate. You’re counting on it.` },
      `The tunnel slopes steadily down. You walk and listen to your own footsteps echoing, and after a long time the pipe widens into a junction.`,
    ],
    choices: [{ text: `Walk on`, to: 'U02' }],
  },
  {
    id: 'U02',
    title: 'The Fork',
    era: 'under',
    onEnter: { set: { viaLowline: true } },
    cast: ['player'],
    imagePrompt: `A junction in a concrete tunnel where two round openings sit side by side, water trickling from both. The player, seen from behind in the black overcoat and fedora, shines a flashlight on one opening and holds a folded paper chart. Alone.`,
    text: [
      `You’ve come to a junction. Your flashlight shows two round openings side by side in the far wall, with water trickling out of both.`,
      `From the right-hand opening comes a cold draft that smells of salt and mud and, very faintly, of diesel. From the left-hand opening comes the smell of old stone and damp cardboard.`,
      { if: is('hasMap'), text: `You take out Mrs. Tilden’s chart and shine your flashlight on it. The right-hand branch is marked OUTFALL TO RIVER. The left-hand one is marked OLD CELLAR SEWER, DISUSED.` },
    ],
    choices: [
      { text: `Take the right-hand tunnel`, to: 'U04' },
      { text: `Take the left-hand tunnel`, to: 'U03' },
    ],
  },
  {
    id: 'U03',
    title: 'Dead End',
    era: 'under',
    cast: ['player'],
    onEnter: cost(15),
    imagePrompt: `The end of a low, crumbling brick tunnel: a wall of collapsed brick with water seeping through, and a rusty iron ladder up to a welded-shut manhole. The player, seen from behind in the black overcoat and fedora, stands in the flashlight beam with bowed head. Alone.`,
    text: [
      `The left-hand tunnel runs on for a long way, getting lower and lower, until you’re walking with your head bowed. Then it ends at a wall of crumbled brick, with water seeping through the rubble and a rusted iron ladder leading up to a manhole cover that has been welded shut.`,
      `There’s nothing here. You go back the way you came, with cold drips running down your neck, and by the time you reach the fork again, you’ve lost a good deal of time. Your lead is down to {{clock}}.`,
    ],
    choices: [{ text: `Go back to the fork`, to: 'U02' }],
  },
  {
    id: 'U04',
    title: 'The Sump',
    era: 'under',
    cast: ['player'],
    imagePrompt: `A concrete tunnel where the floor dips into a twenty-foot stretch of black water wall to wall. Beyond it a dry ledge, and a steel pipe bolted along the ceiling. The player, seen from behind in the black overcoat and fedora, stands at the water’s edge with a flashlight. Alone.`,
    text: [
      `The right-hand tunnel runs downhill, and the draft grows colder and stronger. Then the floor falls away. The tunnel dips in a long, low curve, and the dip is full of black water from wall to wall for about twenty feet. It looks about waist-deep on you, and it moves slowly toward the river.`,
      `On the far side, the floor climbs out of the water onto a dry concrete ledge. Above the water, a steel pipe runs along the tunnel roof, bolted into the walls at both ends.`,
    ],
    choices: [
      { text: `Fire Data’s rope launcher at the pipe and swing across`, to: 'U05', if: is('hasRope') },
      { text: `Wade through the cold water`, to: 'U05', set: { soaked: true }, ...cost(15) },
    ],
  },
  {
    id: 'U05',
    title: 'The Grate',
    era: 'under',
    cast: ['player', 'sloth'],
    imagePrompt: `A heavy iron grate with bars as thick as wrists across a concrete tunnel. On its far side Sloth, huge and beaming, takes the grate in both hands to lift it. The player, seen from behind in the black overcoat and fedora, holds up a flashlight on the near side.`,
    text: [
      { if: is('soaked'), text: `Your clothes are heavy and freezing, and your teeth are chattering.`, else: `You’re cold, but you’re across and still dry.` },
      `A hundred yards past the water, the tunnel is blocked by a heavy iron grate set in a frame, with bars as thick as your wrist from floor to ceiling. Beyond it, the tunnel carries on, and river air comes through the bars.`,
      {
        if: is('slothPlan'),
        text: `On the far side, a huge shape is sitting on the floor with its knees drawn up, humming to itself. When your flashlight finds it, it springs to its feet and nearly hits the roof. “Friend!” says Sloth, beaming. You pass the chocolate bar through the bars, and it disappears in one bite. “Sloth lift,” he says happily.`,
        else: `In one corner the frame has rusted away, leaving a gap. It looks just big enough for you.`,
      },
    ],
    choices: [
      { text: `Let Sloth lift the grate`, to: 'U06', if: is('slothPlan'), set: { slothWith: true } },
      { text: `Squeeze through the gap`, to: 'U06', if: not(is('slothPlan')), ...cost(15) },
    ],
  },
  {
    id: 'U06',
    title: 'The Outfall',
    era: 'under',
    cast: ['player', 'sloth'],
    imagePrompt: `The mouth of a concrete outfall tunnel opening onto the dark underside of a wooden pier: a drowned forest of black pilings in fog, with a narrow catwalk bolted to the posts above the water and orange lamplight leaking through the planks overhead. The player, seen from behind in the black overcoat and fedora, stands in the opening.`,
    text: [
      `The tunnel bends, climbs a little and ends in a round concrete mouth, the outfall, which opens straight onto the river. Cold wind blows in your face. Ahead is the dark, wet space under a wooden pier: a forest of black pilings going away into the fog, with a narrow catwalk bolted to the posts a few feet above the water. Above you, planks creak. You’re under the Seventh Street Pier.`,
      { if: is('slothWith'), text: `Sloth ducks to fit through the outfall behind you, his shoulders brushing the concrete, and straightens very slowly under the planks, as if he knows how loud he could be. He puts one huge finger to his lips.` },
      `You switch off your flashlight. A little orange light comes through the gaps overhead, from a lamp on the pier above, and with it come voices.`,
    ],
    choices: [{ text: `Step out onto the catwalk`, to: 'P01' }],
  },

  // ── WATERFRONT ───────────────────────────────────────────────
  {
    id: 'P01',
    title: 'Under the Pier',
    era: 'pier',
    time: 'THU OCT 31 · EVENING',
    cast: ['player', 'sloth'],
    imagePrompt: `The underside of a long wooden pier in fog at high water: black pilings rising like a drowned forest, a narrow wet catwalk a few feet above slapping water, orange lamplight leaking through the planks. At the far end of the catwalk a rusty iron door in a stone footing is half under water. The player, seen from behind in the black overcoat and fedora, crouches on the catwalk. Sloth, if present, crouches beside them.`,
    text: [
      `You’re on the catwalk under the Seventh Street Pier, a narrow walkway of wet boards bolted to the pilings a few feet above the water. All around you, the pilings rise like the trunks of a drowned forest. The river is high. It slaps at the posts just below your feet and runs up them in dark, shining stripes, with a skin of oily foam. Fog drifts in off the water.`,
      { if: is('soaked'), text: `You’re soaked to the skin and shivering, which does nothing for your nerves.` },
      {
        if: is('viaLowline'),
        text: `Beside you, a rusty iron ladder runs up through a gap in the planks to the pier deck.`,
        else: `Beside you is the ladder you came down, running up through the planks to the pier deck.`,
      },
      `Overhead, the planks creak under boots. Two men are walking along the pier, and their voices carry down through the gaps. You can’t make out the words, but you can guess whose voices they are.`,
      {
        if: is('hasMap'),
        text: `At the far end of the catwalk, the boards stop, and a rusty iron door stands in the stone footing of the pier, exactly where Mrs. Tilden’s chart put it. The bottom half of the door is under black water.`,
      },
      {
        if: all(not(is('hasMap')), is('foundDoor')),
        text: `At the far end of the catwalk, the boards stop at a wall of old stone footing. You know there’s an iron door in it, because you felt it under the black water, and the water still covers most of it.`,
      },
      {
        if: all(not(is('hasMap')), not(is('foundDoor'))),
        text: `At the far end of the catwalk, the boards stop at a wall of old stone footing, furred with weed and barnacles. A lot of black water is moving against it.`,
      },
      { if: is('slothWith'), text: `Sloth crouches beside you. The catwalk is sagging under him, and he’s holding his breath, as if that might make him lighter.` },
      { if: all(is('slothPlan'), not(is('slothWith'))), text: `You can’t help wondering whether Sloth is still waiting for you at his grate.` },
      `The Fratellis don’t know you’re down here, but they’re close, and your lead is {{clock}}.`,
    ],
    choices: [
      { text: `Wade out into the water now`, to: 'P02' },
      { text: `Settle in among the pilings and keep out of sight`, to: 'P03', if: { any: [is('hasMap'), is('foundDoor')] }, ...cost(15) },
      { text: `Feel along the pilings for whatever the key might open, keeping out of sight`, to: 'P03', if: all(not(is('hasMap')), not(is('foundDoor'))), ...cost(25) },
      { text: `Climb the ladder to the pier deck and look for another way to whatever the key opens`, to: 'E05' },
    ],
  },
  {
    id: 'P02',
    title: 'Chest-Deep',
    era: 'pier',
    cast: ['player'],
    imagePrompt: `The player, seen from behind in the black overcoat and fedora, chest-deep in black water along a slimy stone footing, one arm braced against the wall, as the current drags at the coat. A rusty iron door is just visible below the surface by flashlight glow. Alone.`,
    text: [
      `You lower yourself off the end of the catwalk. The water is up to your chest in one step, so cold it stops your breath, and the current pulls at your coat like a hand.`,
      {
        if: is('hasMap'),
        text: `You wade along the stone footing with one arm against the wall to the iron door you can see: flat, slimy with weed, its top half just above the surface.`,
        else: `You wade along the stone footing with one arm against the wall. A few yards on, your hand finds iron under the surface: a flat iron door, slimy with weed.`,
      },
      `It has no lock to fight with, but the weight of the water holds it shut, and the handle is a long way down. To get it open, you’d have to put your whole head under, hold on to the door against the current and haul.`,
      `The water tugs harder. Your coat has begun to fill and drag.`,
    ],
    choices: [
      { text: `Take a deep breath and dive to haul the door open`, to: 'E04' },
      { text: `Back out while you still can`, to: 'P01', set: { soaked: true, foundDoor: true }, ...cost(10) },
    ],
  },
  {
    id: 'P03',
    title: 'Waiting',
    era: 'pier',
    time: 'THU OCT 31 · 9:00 PM',
    cast: ['player', 'sloth'],
    imagePrompt: `A dark space between two pilings under a pier, the player, seen from behind in the black overcoat and fedora, curled on a crossbeam above the water, watching a wet line on the wood. Far above, fog and a faint orange lamp through the planks. Sloth, if present, sits beside them with one huge hand hovering protectively.`,
    text: [
      {
        if: { any: [is('hasMap'), is('foundDoor')] },
        text: `You find a dry spot on a crossbeam between two pilings, well back from the catwalk where the lamp from the pier above can’t reach, and settle in to wait. You know where the door is. All you have to do is stay out of sight until you can reach it.`,
        else: `You work your way along the pilings, hand over hand in the dark, looking for anything with a lock. The stone footing runs on for a long way, and you feel along all of it. You find barnacles, weed, a dead crab and a rusty hook. Then, at last, your fingers find a flat square of iron set into the stone, its lower half underwater. You back away and settle on a crossbeam to wait.`,
      },
      `It’s a long, cold, dripping wait. The tide goes out so slowly you can only see it happen by fixing your eyes on a piling and counting. The wet line on the wood creeps down by a finger’s width, and then another. The water drops away from the stone, from the catwalk, from the iron of the door.`,
      { if: is('soaked'), text: `You’re shaking so hard your teeth rattle. You press your hands under your arms and clench your jaw.` },
      { if: is('slothWith'), text: `Sloth sits patiently beside you the whole time. Once, when a board creaks overhead, he holds his breath until it stops.` },
      `Far away across the flats, a church bell strikes nine.`,
    ],
    choices: [{ text: `Keep still and listen`, to: 'P04' }],
  },
  {
    id: 'P04',
    title: 'Voices Overhead',
    era: 'pier',
    cast: ['player', 'sloth'],
    imagePrompt: `Looking up from under a pier through gaps between planks: orange lamplight, two silhouetted men standing close, one burly, one thin, one holding a flashlight. The player, seen from behind in the black overcoat and fedora, looks up from a crossbeam. Sloth, if present, sits beside them very still.`,
    text: [
      `A little after the bell, the footsteps stop right above you, and the voices come down through the gaps between the boards, close enough to make out.`,
      `“What time is it, Francis?” asks a heavy, gravelly voice.`,
      `“Nine,” answers a sharper, whinier one. “Mama’s boat is due at quarter past. Low water’s at nine forty-one. The second the tide’s off that door, we go down and cut it open, Jake.”`,
      `“And if the kid in the black coat turns up?” says the heavy voice, which must be Jake’s.`,
      `“Then we take the key and save ourselves ten minutes,” says Francis. “If not, we cut. The fireworks will cover the noise. Once the bonfire’s lit, nobody’s going to hear a torch.”`,
      { if: is('hasMap'), text: `“It was the deputy suit,” Jake mutters. “I told you the kid would smell it.” “I looked great in that suit,” says Francis.` },
      { if: is('slothWith'), text: `Beside you, Sloth has gone very still at the sound of his brothers’ voices. You touch his sleeve, and he lets out a long, slow breath.` },
      `So that’s their plan. They’ll be at the door at low water too, and you’ll have to be faster than they are.`,
    ],
    choices: [{ text: `Keep waiting`, to: 'P05' }],
  },
  {
    id: 'P05',
    title: 'The Boat Comes In',
    era: 'pier',
    time: 'THU OCT 31 · 9:15 PM',
    cast: ['player', 'mama', 'sloth'],
    imagePrompt: `Fog on the river at night. A battered wooden fishing boat with a small wheelhouse and one bright spotlight slides alongside the end of a pier, a rope thrown up. On the planks above, the silhouette of a stout woman in a fur-collared coat with a handbag. Below the pier, the player, seen from behind in the black overcoat and fedora, watches from the pilings.`,
    text: [
      `At quarter past nine, you hear an engine out on the water. A beam of white light swings across the fog, and an old wooden fishing boat, the *Rosalie*, comes sliding in alongside the end of the pier with her spotlight sweeping. A rope goes up. Boots thump on the planks.`,
      `You can’t see her, but you hear her. “Boys,” says a voice, dry and level and very used to being obeyed. Mama Fratelli. “Anything?”`,
      `“No key, Mama,” says Jake. “The kid’s still out there somewhere.”`,
      `“Then we cut. Jake, get the torch. Francis, stay by the ladder.” Her heels click on the boards above you. “And when we’ve got my plates,” she says, “we’re going to collect Sloth. A family belongs together.”`,
      { if: is('slothWith'), text: `Beside you, Sloth is trembling. You find his huge hand in the dark and hold it, and after a while the trembling slows.` },
    ],
    choices: [{ text: `Wait for the tide`, to: 'P06' }],
  },
  {
    id: 'P06',
    title: 'Low Water',
    era: 'pier',
    time: 'THU OCT 31 · 9:41 PM',
    cast: ['player', 'sloth'],
    imagePrompt: `Low tide under the pier: bare black pilings above a flat of wet sand, and a rusty iron door in the stone footing now completely clear of the water. Far across the flats an orange glow flares under the fog and a green-gold firework bursts. The player, seen from behind in the black overcoat and fedora, runs along the catwalk toward the door. Sloth, if present, follows.`,
    text: [
      `At 9:41 PM, by your watch, the tide is as low as it will go. The pilings stand bare and black above a flat of wet sand, and the stone footing at the end of the catwalk is dry to its base. The iron door you’ve been staring at for an hour stands completely clear of the water, streaming and rusty, with its padlock long gone.`,
      `A roar goes up from far across the flats: the bonfire has been lit. Light flickers orange along the underside of the fog, and a moment later the first firework thumps into the sky and bursts green and gold.`,
      `Overhead, boots pound the planks. “That’s it!” Jake shouts. “Tide’s out! Let’s go!” The Fratellis are about to come down.`,
      `You’re nearer the door than they are, and you have the key.`,
    ],
    choices: [{ text: `Run to the iron door`, to: 'P07' }],
  },
  {
    id: 'P07',
    title: 'Locker Seven',
    era: 'pier',
    onEnter: { set: { hasPlates: true } },
    cast: ['player', 'plates', 'sloth'],
    imagePrompt: `Inside a cold stone-arched ice house lined with rusty numbered metal lockers. The player, seen from behind in the black overcoat and fedora, lifts a cracked biscuit tin out of open locker 7 and unwraps a pillowcase to show two engraved copper plates glinting in the flashlight. Sloth, if present, fills the doorway behind them.`,
    text: [
      `The iron door scrapes open when you put your shoulder to it. You slip through.`,
      `Inside is a low stone room with an arched ceiling, cold as a refrigerator. The walls are lined with rusted metal lockers, each with a number painted on the door in faded white. You find 7 at once. The key turns with a screech of rust.`,
      `Inside the locker is a cracked biscuit tin, and inside the tin, wrapped in a pillowcase, are two flat plates of engraved copper, heavy and cold, covered in tiny lines. Held up to your flashlight, the pattern becomes a face, in mirror image: the portrait from a twenty-dollar bill. On the pillowcase, in marker, someone has written: MAMA’S. HANDS OFF.`,
      { if: is('slothWith'), text: `Sloth stands in the doorway behind you, his shoulders filling it, so that nobody could get in while you work.` },
      `You tuck the plates inside your overcoat. Outside, boots are pounding on the ladder.`,
    ],
    choices: [{ text: `Go back out`, to: 'P08' }],
  },
  {
    id: 'P08',
    title: 'Company',
    era: 'pier',
    cast: ['player', 'jake', 'francis', 'mama', 'sloth'],
    imagePrompt: `Wet moonless sand flats beside a pier, fireworks bursting in fog. Jake and Francis run across the mud toward the player, who is seen from behind in the black overcoat and fedora, holding the front of the coat closed. Above on the pier’s end a stout woman in a fur-collared coat leans on the rail with a handbag. Sloth, if present, steps out between the player and the brothers with his arms spread.`,
    text: [
      `When you come out of the ice house, Jake and Francis are on the sand twenty yards away, running at you across the mud. A little farther back, at the end of the pier above, you can see the silhouette of a stout woman in a fur-collared coat, leaning on the rail beside a handbag, watching.`,
      `“Evening, dear,” calls Mama Fratelli. Her voice carries as if she were in the next room. “That’s a very nice coat. I’d like it back, and whatever’s in it.” She smiles. “Hand it over, and we’ll leave Astoria tonight and never come back. You have my word.”`,
      { if: is('slothWith'), text: `Sloth steps out of the ice house into the open, between you and his brothers, with his arms spread wide. Jake and Francis skid to a halt.` },
      `Behind you, along the pilings, is the round mouth of a concrete outfall tunnel. Ahead is a hundred yards of firelit mud, with the flames of the bonfire glowing in the fog. To your right, the sand ends where the river’s deep channel runs black and fast.`,
    ],
    choices: [
      { text: `Run out across the open flats toward the glow and the noise`, to: 'F01' },
      { text: `Dive back into the outfall and the tunnel`, to: 'F02' },
      { text: `Run to the edge of the sand and throw the plates into the deep channel`, to: 'E08' },
      { text: `Give Mama the plates and take her at her word`, to: 'E07' },
    ],
  },

  // ── FINALE ───────────────────────────────────────────────────
  {
    id: 'F01',
    title: 'Across the Flats',
    era: 'pier',
    cast: ['player', 'jake', 'sloth'],
    onEnter: cost(20),
    imagePrompt: `A wide shot of the player, seen from behind in the black overcoat and fedora, sprinting across wet sand toward a distant orange glow in the fog, a firework bursting overhead. Behind them, Jake stumbles in the mud. Sloth, if present, lopes alongside with long strides.`,
    text: [
      `You run. The wet sand sucks at your sneakers and the plates bang against your ribs. Behind you, boots slap the mud, and Jake roars at you to stop. Ahead, the glow of the fire grows, and the fog turns orange.`,
      { if: is('slothWith'), text: `Sloth runs beside you in huge, loping strides. When Jake gets close enough to snatch at your coat, Sloth simply puts out one arm, and Jake runs into it like a wall and sits down.` },
      `You run for what seems like a very long time.`,
      { if: ge(1), text: `Then the fog tears open, and you burst out of it into the light. You’ve kept a margin of {{clock}}.` },
    ],
    choices: [{ text: `Run into the crowd`, to: 'F03' }],
  },
  {
    id: 'F02',
    title: 'The Long Way',
    era: 'under',
    cast: ['player', 'francis', 'sloth'],
    onEnter: cost(25),
    imagePrompt: `Inside a concrete tunnel by flashlight. The player, seen from behind in the black overcoat and fedora, runs uphill through ankle-deep water, clutching the front of the coat closed. Behind them a heavy iron grate swings down across the tunnel and Francis, in a loud checked sport coat, is stuck against its bars. Sloth, if present, holds the grate.`,
    text: [
      {
        if: is('viaLowline'),
        text: `You dive back along the catwalk and into the outfall with the plates inside your coat, and you pelt up the tunnel as fast as you can go. The dip where the water was deep has drained to a puddle with the tide, and you splash straight through it.`,
        else: `You run along the catwalk to the round mouth of the concrete outfall tunnel. It must lead uphill, into the town. You dive in with the plates inside your coat and pelt up the tunnel as fast as you can go. A dip in the floor, drained to a puddle by the tide, splashes under your feet.`,
      },
      { if: is('slothWith'), text: `Sloth ducks in after you, scraping the concrete, and lopes along at your shoulder.` },
      `Jake tries to follow head-first, still clutching the torch case, and wedges it crossways in the mouth of the outfall, sticking fast and bellowing. Francis wriggles past him and comes after you, shouting that he’s going to count to three.`,
      {
        if: is('slothWith'),
        text: `At the grate, Sloth takes the bars in both hands, heaves the grate up, lets you through and swings it down behind you with a clang that echoes for a hundred yards. Francis hits the bars and sits down. “Sloth,” he says, in a very small voice. Sloth looks at his shoes.`,
      },
      {
        if: all(is('slothPlan'), not(is('slothWith'))),
        text: `A heavy iron grate blocks the tunnel, and beside it, to your astonishment, a huge shape rises from the floor. It’s Sloth, who has been waiting here all evening. He takes the bars in both hands, heaves the grate up, lets you through and swings it down behind you with a clang that echoes for a hundred yards. Francis hits the bars and sits down. “Sloth,” he says, in a very small voice. Sloth looks at his shoes, then folds his arms and settles down by the grate to make sure nobody else comes through.`,
      },
      {
        if: not(is('slothPlan')),
        text: `A heavy iron grate blocks the tunnel. You squeeze through a gap in one corner, and when Francis tries to follow, his checked sport coat catches on a rusty bar. He stays stuck, swearing, until you’re out of earshot.`,
      },
      { if: all(is('slothWith'), ge(1)), text: `Sloth peels off into a side tunnel that leads home to the hatch behind Chunk’s garage, with a wave.` },
      `You run on until your lungs burn, come out at the arch at the bottom of the Goon Docks and keep on running, down through the town to the police station on Duane Street.`,
      { if: ge(1), text: `Behind the counter, a heavy desk sergeant whose nameplate says OLAFSEN, a phone at each ear, looks up at the sight of you, muddy and out of breath, with an engraved copper plate in each hand.` },
    ],
    choices: [{ text: `Put the plates on the counter`, to: 'E09' }],
  },
  {
    id: 'F03',
    title: 'The Crowd',
    era: 'pier',
    cast: ['player', 'mikey', 'data', 'chunk', 'mouth', 'sloth'],
    imagePrompt: `A huge bonfire of pallets and driftwood on river flats, sparks flying into fog, fireworks overhead, hundreds of people in costumes (witches, ghosts, a hamburger, a gorilla) mid-laugh. The player, seen from behind in the black overcoat and fedora, holds two copper plates above their head. Mikey, Data, Chunk and Mouth push through the crowd toward them. A broad man in a tan uniform and campaign hat turns from a cider table.`,
    text: [
      `The Halloween bonfire is a mountain of burning pallets and driftwood, throwing sparks up into the fog. Around it, hundreds of people in costumes are laughing and eating hot dogs: witches, ghosts, a very convincing hamburger. A brass band is playing. Fireworks are bursting overhead.`,
      `“Help!” you shout, holding up the plates. “The Fratellis! It’s the Fratellis!”`,
      `A man in a gorilla suit gives you a thumbs-up. “Great costume!” he says. A woman dressed as a cat tells her husband you’re the best one yet. Nobody believes a word.`,
      `Then a hand grabs your shoulder and you spin around. It’s Mikey, with Data, Chunk and Mouth at his heels, and Mikey’s father a few steps behind them with a paper cup of cider. “Fratellis?” says Mikey. “Where?” You point. Out of the fog behind you come Jake and Francis, running.`,
      { if: is('slothWith'), text: `Chunk has already thrown his arms around Sloth, who is still at your side, puffing like a steam engine. “You came!” Chunk yells. Sloth beams.` },
      `“Sheriff!” Mikey’s father bellows. A broad man in a tan uniform and a campaign hat has turned from the cider table. That’s Sheriff Pruitt. You thrust the plates toward him.`,
      {
        if: ge(15),
        text: `You’re just fast enough. Jake and Francis run out of the fog and into a crowd of several hundred people, in front of the sheriff, with their faces on every front page in the county. Jake slows. Francis tries to turn around. A deputy is already standing behind each of them.`,
        else: `You’re not quite fast enough. A heavy hand closes on your collar from behind. The plates are knocked out of your grip, and they go spinning through the air toward the fire.`,
      },
    ],
    choices: [
      { text: `Watch what happens next`, to: 'E11', if: ge(15) },
      { text: `Watch what happens next`, to: 'E10', if: le(14) },
    ],
  },

  // ── ENDINGS ──────────────────────────────────────────────────
  {
    id: 'E01',
    title: 'Trick or Treat',
    era: 'docks',
    time: 'THU OCT 31 · 7:30 PM',
    ending: { kind: 'bad' },
    cast: ['player', 'chunk', 'mouth', 'mama', 'jake', 'francis'],
    imagePrompt: `A house porch at night with a jack-o’-lantern. The player, seen from behind in the black overcoat and fedora, sits on a porch swing with Chunk and Mouth, all three with their sneaker laces tied together. A stout woman in a fur-collared coat holding a handbag smiles on the steps, with Jake and Francis behind her and a white laundry van with a blue stripe at the curb.`,
    text: [
      `You tuck the key into a sock at the bottom of your drawer, and you, Chunk and Mouth go trick-or-treating as if nothing had happened. It’s a good night for candy. The three of you are back at your house by seven-thirty with full bags, and you’re halfway through a chocolate bar on the porch when a white van with a blue stripe pulls up across the street.`,
      `Three people get out: a burly man in a leather jacket, a thin, angry-looking man in a checked sport coat, and between them a stout old woman in a fur-collared coat with a handbag over one arm. They come up your walk. The woman rings the bell, though you’re sitting right there. “Trick or treat,” says Mama Fratelli, with a smile like a drawer closing.`,
      `“We’re collecting for a charity,” she says. “It’s called Mama’s Missing Property. I believe you bought my husband’s overcoat.”`,
      `By nine o’clock the Fratellis have the coat, the key and the whole story. You, Chunk and Mouth are sitting on your porch swing with your sneaker laces tied together, watching the van’s taillights go down the hill. At low tide they open a locker in an old ice house under the Seventh Street Pier with your key, quietly and in under a minute. Over the next year, fake twenties turn up in every cash register in Clatsop County.`,
    ],
  },
  {
    id: 'E02',
    title: 'A Helpful Deputy',
    era: 'town',
    ending: { kind: 'bad' },
    cast: ['player', 'deputy'],
    imagePrompt: `The wet library steps at night. A man in a tan deputy’s uniform and crooked fake mustache climbs into a white laundry van with a blue stripe, a brass key glinting in his glove. The player, seen from behind in the black overcoat and fedora, sits heavily on the steps. Alone.`,
    text: [
      `You hold out the key. The deputy takes it between two gloved fingers, looks at the tag and smiles. “Good citizen,” he says. “Thank you, kid. We’ll take it from here.”`,
      `He walks back to the van and drives away, with the radio crackling. Mrs. Tilden comes out onto the steps with a mug of cocoa. “Who was that?” she asks.`,
      `“The deputy,” you say.`,
      `She frowns. “But the sheriff’s office said they couldn’t send anyone before nine.”`,
      `You think about the white van with the blue stripe, and about the radio bulletin, and you sit down heavily on the library steps. At low tide an ice house door under the Seventh Street Pier opens, and with the key it takes the Fratellis less than a minute. They’re halfway to the border before anyone checks the locker. In the months that follow, fake twenties turn up in every cash register in Clatsop County, and every time you see one, you remember the mustache.`,
    ],
  },
  {
    id: 'E03',
    title: 'The Evidence Drawer',
    era: 'town',
    ending: { kind: 'bad' },
    cast: ['player'],
    imagePrompt: `A police station front desk at night. A tired desk sergeant drops a small brown envelope marked EVIDENCE into a metal drawer and slides it shut. The player, seen from behind in the black overcoat and fedora, watches from the counter with a doubtful slump.`,
    text: [
      `Sergeant Olafsen slips the key into a small brown envelope, writes EVIDENCE across it and drops it into a drawer. “Monday morning,” he says. “First thing. Happy Halloween, kid.”`,
      `You walk home through the drizzle with a strange, empty feeling. At nine, the deputies leave their roadblocks and drive down to the river flats, where the bonfire is lit and the fireworks start. And while everybody is looking up at the fireworks, three people climb down a ladder under the Seventh Street Pier and cut open an old ice-house locker with a torch.`,
      `On Monday morning the sergeant opens the drawer and looks at the envelope for a long time. By then the locker has been open and empty since Thursday night, and a fishing boat called the *Rosalie* has been seen heading out over the bar, riding low in the water. The Fratellis are never found. Fake twenties turn up in every cash register in Clatsop County, and nobody at the station ever connects the envelope in the drawer with the empty locker under the pier.`,
    ],
  },
  {
    id: 'E04',
    title: 'High Water',
    era: 'pier',
    ending: { kind: 'bad' },
    cast: ['player'],
    imagePrompt: `A dark river at night. A harbor patrolman dressed as a bedsheet ghost hauls the player, dripping, out of the water into a small boat by the back of the black overcoat. A fedora floats nearby. Bonfire glow in the distant fog.`,
    text: [
      `You take the biggest breath of your life, let go of the wall and duck under.`,
      `The water is black and so cold it feels like being hit. You find the handle by feel and heave, and the current drags the door open an inch and slams it again, and the key slips out of your numb fingers and vanishes. You grab for it and let go of the door. After that there’s only the current, which has been waiting for you.`,
      { if: is('slothWith'), text: `Sloth reaches for you from the catwalk and just misses. He runs along the pilings shouting for help in the biggest voice in Astoria, and it’s his shouting that brings the patrol boat.` },
      `You’re fished out of the river a quarter of a mile away by a harbor patrolman who has come down to the bonfire dressed as a ghost. He wraps you in a blanket and drives you to the hospital with his sheet still on. You’re fine, after two days of hot soup. The key is at the bottom of the Columbia River, and at low tide three people climb down a ladder with a torch and find the locker waiting for them. You never find out what happened to the plates, but every cash register in Clatsop County does.`,
    ],
  },
  {
    id: 'E05',
    title: 'Caught on the Pier',
    era: 'pier',
    ending: { kind: 'bad' },
    cast: ['player', 'francis', 'jake', 'sloth'],
    imagePrompt: `Night on a pier deck. Two flashlight beams pin the player, seen from behind in the black overcoat and fedora, against a chain-link fence. A thin man in a loud checked sport coat grins and a burly man in a leather jacket rests a heavy hand on the player’s shoulder.`,
    text: [
      `A flashlight beam finds you before you’ve gone ten feet. “Well, well,” says Francis Fratelli, in the voice of a man who has been waiting all evening for something to go right. “Look who’s out trick-or-treating.” A second beam finds you from the other side, and Jake’s heavy hand lands on your shoulder.`,
      { if: is('slothWith'), text: `Below you on the ladder, Sloth can’t get past to help. With Jake’s hand on your shoulder, there’s nothing for it but to climb the rest of the way, and Sloth comes up after you with his hands raised.` },
      `They take the key out of your pocket in two seconds. They lock you in the tool shed at the foot of the pier with the door wedged, and when the fireworks start hours later, you hear boots going down the ladder under the pier, and a rusty locker door squealing open.`,
      { if: is('slothWith'), text: `Sloth goes into the shed with you, and sits in the dark with his arm round your shoulders until you’re let out.` },
      `It’s eleven o’clock before some trick-or-treaters hear you banging and let you out. By then a fishing boat called the *Rosalie* is a long way out on the river, and the Fratellis, the plates and the key are gone. You’ve learned a few things, though, mainly about walking straight up to a Fratelli.`,
    ],
  },
  {
    id: 'E06',
    title: 'Out of Lead',
    era: 'docks',
    ending: { kind: 'bad' },
    cast: ['player', 'jake', 'francis', 'sloth'],
    imagePrompt: `A dark, wet street at night. The player, seen from behind in the black overcoat and fedora, is caught in a flashlight beam with a burly man in a leather jacket holding up a small brass key to the light. A thin man in a checked sport coat grins beside him.`,
    text: [
      `You’ve been running, ducking and doubling back for so long that you haven’t noticed how close the Fratellis have come. Then there’s a flashlight in your face, a heavy hand on your coat collar and a voice in your ear that says, “Gotcha.”`,
      {
        if: is('hasPlates'),
        text: `Jake opens your coat, takes out the plates with two fingers, holds one up to the light and gives a low whistle. “Mama’s going to be happy,” he says.`,
        else: `Jake takes the key from your pocket with two fingers, holds it up to the light and gives a low whistle. “Mama’s going to be happy,” he says.`,
      },
      { if: is('slothWith'), text: `Sloth manages to lift Francis off the ground, but he’s much too gentle to do anything more, and when Jake says his name in a particular tone, he puts Francis down and stands there with his head hanging. The Fratellis leave without him, and when the van pulls away he walks home to Chunk’s garage.` },
      `By the time anyone finds you, the Fratellis are long gone, with a fifty-mile start and everything they came for. Somewhere along the way, you let them catch up.`,
    ],
  },
  {
    id: 'E07',
    title: 'Just Asking Nicely',
    era: 'pier',
    ending: { kind: 'bad' },
    cast: ['player', 'mama', 'sloth'],
    imagePrompt: `Foggy river night. The player, seen from behind in the black overcoat and fedora, hands two copper plates up to a stout woman in a fur-collared coat at the foot of a pier ladder; she tucks them into her handbag with a gentle smile. A battered fishing boat idles behind with a spotlight.`,
    text: [
      `You walk across the mud to the foot of the pier ladder. Mama Fratelli climbs down it, with Jake steadying her, and you hand her the plates.`,
      `“There,” says Mama, patting your cheek. “That wasn’t so hard, was it? You’re a sensible child.” She puts the plates in her handbag. “And you’ll see I keep my word. We’ll be out of Astoria tonight.”`,
      { if: is('slothWith'), text: `Sloth is standing beside you. Mama holds out a hand to him. “Come along, baby,” she says. Sloth looks at the hand, and at you, and at his brothers. Then he takes a long step backward and says, quietly, “Sloth stay.” Mama’s smile twitches. “Suit yourself,” she says.` },
      `The laundry van’s engine starts at the foot of the pier, and it slides off into the fog with its lights out, leaving the *Rosalie* stuck on the mud. By the time you’ve caught your breath and found anyone to tell, it’s long gone. Mama keeps her word about leaving Astoria. She never said anything about leaving the printing business. Over the next year, fake twenties turn up in every cash register from here to California, and the police can’t work out where they’re coming from.`,
    ],
  },
  {
    id: 'E08',
    title: 'Gone with the Tide',
    era: 'pier',
    ending: { kind: 'good' },
    cast: ['player', 'jake', 'francis', 'mama', 'sloth'],
    imagePrompt: `A wide shot at the edge of the wet sand where the river drops into black water. The player, seen from behind in the black overcoat and fedora, hurls two copper plates in a long glinting arc over the water under a green-gold firework. Behind them, Jake and Francis skid to a halt in the mud and a stout woman in a fur-collared coat gapes from the pier.`,
    text: [
      `You turn and run to the edge of the sand, where the mud drops away into the black, fast water of the river’s channel. Jake lunges. You throw the plates as far as you can.`,
      `They sail out over the dark in a long, flat arc, turning over once in the light of the fireworks, and drop without a splash into the deepest part of the Columbia. They’re gone. A hundred feet of cold water and a hundred years of silt will never give them back.`,
      `Behind you, Mama screams from the rail of the pier. It’s a high, thin sound, like a kettle. Jake and Francis stand at the water’s edge, staring at the river, too stunned to move.`,
      { if: is('slothWith'), text: `Sloth hoists you onto his shoulders and carries you off toward the bonfire for cider and hot dogs.` },
      `The three furious Fratellis pile into the laundry van and drive off into the dark, leaving the *Rosalie* stuck on the mud and nothing to print with, and by the time you’ve found anyone to tell, they’re long gone. They’re never seen in Astoria again. The police never find out what was in the locker. Only a few Goonies ever know. Mikey says it’s the best secret the Goonies have ever kept.`,
    ],
  },
  {
    id: 'E09',
    title: 'Chain of Evidence',
    era: 'town',
    ending: { kind: 'good' },
    cast: ['player', 'mama', 'sloth'],
    imagePrompt: `Night at the foot of a pier. Six deputies’ flashlights switch on at once around three figures with gas cylinders and a cutting torch, caught mid-step on a ladder. A stout woman in a fur-collared coat clutches a handbag in the glare. The player, seen from behind in the black overcoat and fedora, stands at the edge of the light beside a heavy desk sergeant.`,
    text: [
      `The sergeant takes one look at the plates in your hands, turns one over under his lamp and goes the color of putty. “That’s the Fratelli job,” he says. “That’s the real thing.” He puts down both phones. “Nobody move. Nobody breathe. Get me the sheriff.”`,
      `It takes a while, forty minutes of which is the sheriff shouting down a radio from the bonfire. But the Fratellis know the plates are gone, and they know you’re somewhere with them, and the *Rosalie* slips away from the pier with her lights off, heading for the open sea.`,
      `She doesn’t get far. At five to midnight, the harbor patrol boat, tipped off by the sheriff’s radio, switches on its searchlight right across the *Rosalie*’s bow. “Evening, Mama,” says a voice over a loudspeaker. “Evening, Jake. Evening, Francis.”`,
      `Mama is the last one handcuffed. In the morning the sergeant tells you what she said as she was led off the boat. She looked back at the town and said, “Tell that child it’s a very nice coat.”`,
      { if: is('slothWith'), text: `In the morning, Chunk finds Sloth asleep on the garage floor with chocolate on his face and a very peaceful smile.` },
    ],
  },
  {
    id: 'E10',
    title: 'Fire Night',
    era: 'pier',
    ending: { kind: 'good' },
    cast: ['player', 'mikey', 'chunk', 'sloth'],
    imagePrompt: `The glowing edge of a bonfire on river flats. A broad sheriff in a tan uniform and campaign hat clamps a hand on a burly man’s shoulder; a deputy has a thin man in a checked sport coat by the elbow. Two copper plates glow red in the embers of the fire. The player, seen from behind in the black overcoat and fedora, holds a hot dog.`,
    text: [
      `The plates land in the heart of the bonfire, and the hand on your collar tightens.`,
      `Sheriff Pruitt is already moving. You’ve never seen a man move so fast. He lays a broad hand on Jake’s shoulder, a deputy takes Francis by the elbow, and the hand on your collar lets go. “Evening, Jake,” says the sheriff. “Quiet night?”`,
      `Mama watches from the end of the pier as a deputy walks down to the *Rosalie*. When the ashes of the bonfire are raked out at dawn, there’s a puddle of melted copper in the middle of them, and nobody will ever print anything with it. The Fratellis go back to prison. Your proof is gone, so the sheriff can only take your word for what the Fratellis were after, but he knows what you did, and he gives you a hot dog and a cup of cider.`,
      { if: is('slothWith'), text: `Chunk gives Sloth a second hot dog, and nobody in the crowd stares at him for more than a moment.` },
    ],
  },
  {
    id: 'E11',
    title: 'The Whole Town Watching',
    era: 'pier',
    ending: { kind: 'good', best: true },
    cast: ['player', 'mikey', 'data', 'chunk', 'mouth', 'sloth'],
    imagePrompt: `A joyous bonfire night on river flats. A broad sheriff holds one engraved copper plate up to the firelight; two deputies hold Jake and Francis by the elbows; hundreds of costumed townsfolk cheer. The player, seen from behind in the black overcoat and fedora, is hoisted onto the shoulders of Mikey, Data, Chunk and Mouth. In the background a stout woman sits furious in a fishing boat stuck on the mud.`,
    text: [
      `Sheriff Pruitt takes the plates from you. He holds one up to the light of the bonfire, and a murmur goes through the crowd as the face of a twenty-dollar bill, reversed, swims out of the copper. “Well, I’ll be,” he says quietly. “It’s the Fratelli plates.”`,
      `Then he turns around. “Jake Fratelli,” he says, in a voice that carries across the whole of the river flats, “and Francis Fratelli. Fancy seeing you here.” The band stops in the middle of a note. Every head in the crowd turns. A deputy takes each of the brothers by the elbow, and the ring of costumed faces around them goes from amusement to something like applause.`,
      `Down on the pier, Mama Fratelli tries to leave on the *Rosalie*. She discovers that the boat, left too long at the end of the pier, has settled on the mud with the falling tide. She sits in it with her handbag in her lap, furious, until a deputy helps her out.`,
      `You’re passed from hand to hand through a crowd of people you’ve known all your life. Mikey’s father shakes your hand. Mouth tells everyone in earshot that he’s just won the costume contest, which isn’t strictly true, but nobody checks.`,
      { if: is('slothWith'), text: `Chunk has hold of Sloth’s arm and won’t let go. Someone starts clapping, and then everyone does, and Sloth, who has never been applauded in his life, looks around with enormous eyes and says, “For Sloth?” “For you,” says Chunk. Sloth’s smile is brighter than the bonfire.` },
      `The plates go into an evidence bag, then into a safe at the county courthouse, and the Fratellis go back to prison for a very long time. At the end of the night, Mikey hands you a cup of cider. “Nice coat,” he says. “Where did you get it?”`,
      `“Two dollars,” you say, “at an auction.” Everyone laughs, and the bonfire burns on until midnight.`,
    ],
  },
];

// Pages that spend lead can leave it at 0 or below. On those pages every choice needs lead >= 1,
// and a generated "Keep running" choice sends the player to E06 instead.
const caught = `Then you hear boots behind you and Francis Fratelli’s whistle, much too close. Whatever you meant to do next, you’ve run out of lead.`;
const caughtOn: Record<string, string> = {
  T08: `Francis looks up from his crate, straight at you, and a second flashlight snaps on behind you. Whatever you meant to do next, you’ve run out of lead.`,
  F02: `Halfway down Duane Street, a white laundry van with a blue stripe swerves to the curb in front of you. They drove round. Whatever you meant to do next, you’ve run out of lead.`,
};
const spends = (e?: Effects) => (e?.add?.lead ?? 0) < 0;
const costly = new Set<string>();
for (const p of raw) {
  if (spends(p.onEnter)) costly.add(p.id);
  for (const c of p.choices ?? []) if (spends(c)) costly.add(c.to);
}
// Pages where the lead can never reach 0 (D02 is before the meter shows; the others are cheap or early detours).
// If the checker reports a guard that never applies, add the page here.
const unguarded = new Set<string>(['D02', 'D06', 'D07', 'T01', 'T03', 'T04', 'T05']);
const guarded = new Set([...costly].filter((id) => !unguarded.has(id)));

const slothWaits: Passage = {
  if: all(is('slothPlan'), not(is('slothWith'))),
  text: `The next morning, Chunk finds Sloth sitting by his grate in the Lowline, and walks him home.`,
};
const waitEndings = new Set(['E02', 'E03', 'E04', 'E05', 'E06', 'E07', 'E08', 'E09', 'E10', 'E11']);

const pages: Page[] = raw.map((p) =>
  p.ending && waitEndings.has(p.id)
    ? { ...p, text: [...p.text, slothWaits] }
    : !guarded.has(p.id) || p.ending
    ? p
    : {
        ...p,
        text: [...p.text, { if: le(0), text: caughtOn[p.id] ?? caught }],
        choices: [
          ...p.choices!.map((c) => ({ ...c, if: c.if ? all(c.if, ge(1)) : ge(1) })),
          { text: `Keep running`, to: 'E06', if: le(0) },
        ],
      },
);

const story: Story = {
  id: 'fratelli-run',
  title: 'The Fratelli Run',
  subtitle: 'A Goonies adventure',
  blurb: `It’s Halloween in Astoria, and the Fratellis have escaped. The key sewn into your thrift-shop overcoat opens something they want very badly. You have a few hours, a head start and the tide to work out where it belongs before they catch you.`,
  start: 'D01',
  eras: {
    docks: { label: 'Goon Docks' },
    town: { label: 'Downtown' },
    under: { label: 'Underground' },
    pier: { label: 'Waterfront' },
  },
  flags: {
    lead: { default: 105 },
    difficulty: { default: 'medium', values: ['easy', 'medium', 'hard'] },
    running: { default: false },
    phoned: { default: false },
    hasRope: { default: false },
    visitedSloth: { default: false },
    slothPlan: { default: false },
    slothWith: { default: false },
    hasMap: { default: false },
    visitedPolice: { default: false },
    visitedDepot: { default: false },
    visitedHideout: { default: false },
    soaked: { default: false },
    viaLowline: { default: false },
    foundDoor: { default: false },
    hasPlates: { default: false },
  },
  ui: { transition: 'vhs' },
  difficultyNotes: {
    easy: 'A bigger head start on the Fratellis, and undo as many choices as you like.',
    hard: 'A smaller head start, and no undo. Every choice is final.',
  },
  // Lead is the Fratellis’ distance behind you. Budget on the best route: rope 10, Sloth 10, drain 10,
  // waiting for low tide 15 (the library costs 10 and saves 10), final run 20 = 75. The best ending needs
  // 15 left after the run, so Hard allows no slips, Medium one and Easy three.
  difficulties: {
    easy: { set: { difficulty: 'easy', lead: 135 } },
    medium: { set: { difficulty: 'medium', lead: 105 } },
    hard: { set: { difficulty: 'hard', lead: 90 } },
  },
  clock: {
    flag: 'lead',
    label: 'FRATELLI LEAD',
    visibleWhen: is('running'),
    allowExpiredOn: [...guarded],
  },
  art: {
    stylePrefix: `Warm 1980s kid-adventure film illustration: clean ink outlines with painted colour, cinematic lighting, expressive faces, 3:2 landscape. No text, lettering or captions anywhere in the image. Never show pirates, skulls, treasure maps, gold coins or ships’ wheels, never show famous film props or vehicles, and no likeness of any real person. Only the characters listed for the scene appear; the Goonies, Sloth and the Fratellis appear only if described below. The setting is Astoria, Oregon, on Halloween night in late October: drizzle, mist, wet streets and fog off the Columbia River, never snow. Goon Docks scenes are dusky blue and amber. Downtown scenes are streetlight orange. Tunnel scenes are green-grey with torch-yellow light. Waterfront scenes are indigo night with orange bonfire glow. Family-friendly and slightly comic: nobody is hurt.`,
    cast: {
      player: `THE PLAYER: a 14-year-old in a long, oversized black wool overcoat with a worn velvet collar, a battered brown fedora, faded jeans and scuffed red high-top sneakers, with a small flashlight on a lanyard round the neck. Shown from behind or over the shoulder with the face hidden, gender-neutral. Always the same black overcoat and brown fedora.`,
      mikey: `MIKEY WALSH: a small, wiry 13-year-old with messy brown hair, a red zip-up windbreaker, jeans and sneakers, an earnest, stubborn look, an inhaler in one hand when worried.`,
      data: `DATA: a small, quick 13-year-old with round glasses, a dark bowl haircut, a yellow rain jacket whose pockets bulge with homemade gadgets and a belt of small tools.`,
      chunk: `CHUNK: a stocky, cheerful, big-hearted 14-year-old with curly dark hair, a striped rugby shirt under a denim jacket and a bag of candy in one hand.`,
      mouth: `MOUTH: a lanky 14-year-old with a mop of dark hair, a wide grin full of braces, a purple hooded sweatshirt and plastic vampire fangs.`,
      sloth: `SLOTH: a towering, broad-shouldered young man with shaggy dark hair, one drooping eyelid, a gentle crooked smile, a big striped shirt and patched overalls. Kind eyes.`,
      mama: `MAMA FRATELLI: a stout, sharp-eyed woman in her sixties with iron-grey hair pinned up, a heavy dark fur-collared coat, a large old-fashioned handbag and a stern squint.`,
      jake: `JAKE FRATELLI: a burly man in his forties with a heavy brow, dark stubble and a battered leather jacket. Gruff and scowling.`,
      francis: `FRANCIS FRATELLI: a thin, hot-tempered man in his thirties with slicked-back dark hair and a loud checked sport coat. Always scowling.`,
      deputy: `FRANCIS FRATELLI IN DISGUISE: a thin man in a tan sheriff’s deputy uniform with a plastic-looking star badge, a broad-brimmed hat pulled low and a slightly crooked fake mustache. A white laundry van with a blue stripe is parked behind him.`,
      key: `THE KEY: a small brass marine locker key, green with salt, on a loop of string with a faded paper tag.`,
      plates: `THE PLATES: two flat, heavy engraved copper printing plates showing a mirror-image portrait, wrapped in a pillowcase inside a cracked biscuit tin.`,
    },
  },
  pages,
};

export default story;
