import type { Cond, Story } from '../../src/engine/types';

const is = (flag: string, value: string | boolean = true): Cond => ({ flag, is: value });
const not = (cond: Cond): Cond => ({ not: cond });
const all = (...conds: Cond[]): Cond => ({ all: conds });
const complete = all(is('escapement', 'spare'), is('hasCell'));

const story: Story = {
  id: 'stopped-clocks',
  title: 'The Stopped Clocks',
  subtitle: 'A Back to the Future adventure',
  blurb: `At 10:04 PM every clock in Hill Valley stops, and the whole town stops with them. Only you and Doc Brown can still move. You have six hours and three eras to find out who did it and to set time running again.`,
  start: 'S01',
  eras: {
    '1885': { label: 'Old West' },
    '1985': { label: 'Present' },
    '2085': { label: 'Future' },
  },
  flags: {
    ranLate: { default: false },
    sawTracks: { default: false },
    pulledClamp: { default: false },
    clockStarted: { default: false },
    minutes: { default: 360 },
    delays: { default: 0 },
    hasKeycard: { default: false },
    safeJammed: { default: false },
    docTurnedBack: { default: false },
    metTannen: { default: false },
    fooledTannen: { default: false },
    rescued: { default: false },
    escapement: { default: 'none', values: ['none', 'spare', 'original'] },
    visited1885: { default: false },
    visited2085: { default: false },
    lastEra: { default: '1985', values: ['1985', '1885', '2085'] },
    sawExhibit: { default: false },
    caughtAt: { default: 'none', values: ['none', 'shop', 'corridor', 'rack'] },
    tannenKnows: { default: false },
    hasCell: { default: false },
    authorityAlerted: { default: false },
  },
  clock: {
    flag: 'minutes',
    label: 'CLAMP SETS IN',
    visibleWhen: is('clockStarted'),
    allowExpiredOn: ['S41'],
  },
  art: {
    stylePrefix: `Graphic-novel illustration: bold black ink linework and cross-hatching over rich painted color, cinematic lighting and composition, 3:2 landscape. No text, lettering or captions anywhere in the image. Mood: 1980s adventure film. Night scenes use wet reflections, sodium-orange streetlights and neon glow. 1885 scenes are warm, dusty amber. 2085 scenes are cool blue and violet with neon accents.`,
    cast: {
      doc: `DOC BROWN: tall, lanky scientist in his late sixties, wild shock of white hair, wide intense eyes, expressive eyebrows, long dark-brown duster coat over a white shirt, brass goggles pushed up on his forehead, a chunky wristwatch.`,
      player: `THE PLAYER: a 16-year-old in a teal-and-white 1980s bomber jacket, faded jeans and white high-top sneakers. Shown from behind or over the shoulder with the face mostly hidden, gender-neutral. From the moment Doc arrives, a leather wrist bracelet with a small humming metal box on it.`,
      rex: `REX TANNEN: a man in his forties from 2085, slicked-back hair, smug grin, fitted silver jumpsuit, a chunky wrist device glowing electric blue.`,
      madDog: `MAD DOG TANNEN: an 1885 outlaw, unshaven, sneering, long dusty duster coat, battered black hat pulled low, gun belt.`,
      train: `THE TIME TRAIN: a black 19th-century steam locomotive heavily modified with chrome time-travel hardware, glowing blue coils along the boiler, hover-conversion wheels, a big brass headlamp and a wooden cab.`,
      clamp: `THE CHRONO-CLAMP: a toaster-sized brushed-silver device bolted around the spindle of giant clock hands, cables running into iron gears, a small glowing green countdown screen, the air around it rippling like heat haze.`,
      stabilizer: `THE TEMPORAL STABILIZER: a brass cage the size of a birdcage, a copper-and-glass coil at its heart, a toothed brass clock wheel in one socket and a palm-sized glowing blue cylinder in another.`,
    },
  },
  pages: [
    // ── ACT 1: 1985 ─────────────────────────────────────────────
    {
      id: 'S01',
      title: 'Special Delivery',
      era: '1985',
      time: 'NOV 12 1985 04:15 PM',
      cast: ['player'],
      imagePrompt: `Late-afternoon autumn light on the steps of a small-town courthouse with a tall clock tower, its clock stopped. The player, orange-foam Walkman headphones around their neck and a clipboard of flyers under one arm, takes a yellowed old envelope from a Western Union courier in a uniform cap. A vintage Western Union car is at the curb.`,
      text: [
        `Hill Valley, California, is a small town: one main street, a movie theater, a diner, a car dealership with a big smiling sign, and in the middle of it all, Courthouse Square. The courthouse is the oldest building in town, and on top of it stands a tall clock tower. Its hands haven’t moved in thirty years.`,
        `It’s Tuesday, November 12th, 1985, a little after four in the afternoon, and the light is going gold over the rooftops. You’re sixteen. You go to Hill Valley High, you own more cassette tapes than is strictly sensible, and twice a week after school you volunteer for the Hill Valley Preservation Society.`,
        `That’s why you’re standing on the courthouse steps with a clipboard, a coffee can for donations and a stack of flyers that say SAVE THE CLOCK TOWER.`,
        `The story is printed on every flyer. On the night of November 12th, 1955, thirty years ago tonight, a bolt of lightning struck the tower at exactly 10:04 PM and stopped the clock dead. Nobody ever fixed it. It has said 10:04 ever since, through thirty summers and thirty winters. Now the town council wants to tear it down and put up something modern. The Preservation Society wants to repair it. So far, the Preservation Society is mostly you.`,
        `Business is slow. A woman with shopping bags takes a flyer to be polite. A kid on a skateboard nearly runs you over. Red, the old man who sleeps on the bench by the bus stop, wakes up long enough to tell you the clock hasn’t worked since 1955 and he likes it that way. Then he goes back to sleep.`,
        `You don’t mind. You’ve always liked the clock tower. When you were little, you thought it had stopped on purpose, as if it was waiting for something. You’ve never told anyone that.`,
        `By half past four the coffee can holds three dollars and a button. You pull your Walkman headphones down around your neck and start packing up. That’s when a car with WESTERN UNION painted on the door pulls up to the curb.`,
        `Western Union is the telegram company, the people who deliver urgent messages by hand. The courier climbs out, checks his clipboard, checks it again, and looks straight at you. Then he says your full name, carefully, as if he’s been practicing it all the way here.`,
        `“This has been in our care for a hundred years,” he says. “Our instructions were very specific: this date, this time, this spot, this person. Sign here, please.”`,
        `You sign. He tips his cap and drives away, and you’re left holding an envelope that’s yellow with age and as soft as cloth. Your name is on the front in faded ink. There’s a wax seal on the back. You break it.`,
        `Inside is a single sheet, written in a hurried, looping hand:`,
        `*Be at the lamppost on the corner of Courthouse Square at 10:03 PM tonight. Not 10:04. 10:03. Stand still. Whatever you see, don’t be afraid. It’s only me.*<br>*— Dr. Emmett L. Brown, 1885*<br>*P.S. When you find two, take the spare.*`,
        `You know the name. Everyone in Hill Valley does. Doc Brown is the crackpot scientist who lives in a garage on Riverside Drive, the one with the big dog and the small explosions. His only real friend seems to be a kid from your school, Marty McFly. A couple of weeks ago Doc disappeared, and Marty won’t say where he went.`,
        `The letter is dated 1885, a hundred years ago. Nobody is that old. It has to be a joke.`,
        `But the paper is real, the seal was real, and the Western Union man didn’t look like he was joking. You read the letter three more times, then look up at the clock tower. It still says 10:04.`,
      ],
      choices: [
        { text: `Be at the square at 10:03 PM`, to: 'S02' },
        { text: `It’s a prank. Go home and forget about it.`, to: 'S03' },
      ],
    },
    {
      id: 'S03',
      title: 'Second Thoughts',
      era: '1985',
      time: 'NOV 12 1985 10:00 PM',
      cast: ['player'],
      imagePrompt: `A 1980s teenager’s bedroom at night, lit by a desk lamp. The player lies on the bed with Walkman headphones on, staring at a yellowed letter on the desk. A digital clock radio glows 10:00. Posters on the walls, a window showing a distant clock tower.`,
      text: [
        `You walk home the long way, past the diner and the dark windows of the car dealership, with the letter in your jacket pocket. Home is a small house on a quiet street on the other side of downtown. Dinner. Homework. A rerun on TV. Up in your room, the letter sits on your desk and you try not to look at it.`,
        `It has to be a prank, maybe somebody from school who’s seen you hanging around the clock tower with a clipboard. The old paper is a nice touch, though. So is the handwriting. And the Western Union man really didn’t seem to be in on any joke.`,
        `At 10:00 PM you’re lying on your bed with your headphones on. The square is a ten-minute walk away, or seven if you run.`,
      ],
      choices: [
        { text: `Grab your jacket and run`, to: 'S02', set: { ranLate: true } },
        { text: `Stay put. It’s a prank.`, to: 'E01' },
      ],
    },
    {
      id: 'E01',
      title: 'Grounded in Time',
      era: '1985',
      time: 'NOV 12 1985 10:04 PM',
      ending: { kind: 'bad' },
      cast: ['player'],
      imagePrompt: `The same teenager’s bedroom, now eerily still and tinted blue: the player frozen on the bed mid-yawn with headphones on, a moth frozen in the air by the lamp. Through the window, far away over the rooftops, a faint flash of light near a clock tower.`,
      text: [
        `You turn the tape over and close your eyes.`,
        `At 10:04 PM the song stops. Not the tape, the song. The note hangs in your ears and never ends. You try to open your eyes and find you can’t. You can’t do anything at all, and you won’t notice. Nobody in Hill Valley will ever notice anything again.`,
        `Across town, a steam whistle blows over an empty street corner. A white-haired man steps down from a locomotive that has no business being there, looks around the empty square, checks his watch, and says something that is probably “Great Scott.”`,
        `A hundred years later, tourists will walk through a perfect copy of your bedroom in a museum called The Frozen Moment, and a guide will point at you and say, “And here we have a typical teenager of the period. Note the headphones.”`,
      ],
    },
    {
      id: 'S02',
      title: '10:03 PM',
      era: '1985',
      time: 'NOV 12 1985 10:03 PM',
      cast: ['player', 'train'],
      imagePrompt: `Night in a small-town courthouse square: the player clings to an old iron lamppost as blue electric sparks crawl across wet pavement. Out of a ring of fire in the air, a flying steam locomotive descends toward the road with its wheels spinning on nothing and its headlamp sweeping the square. The clock tower looms behind.`,
      text: [
        {
          if: is('ranLate'),
          text: `You run the whole way through dark, empty streets and make it with a stitch in your side and about thirty seconds to spare.`,
          else: `You spend the evening watching the clock on your bedroom wall. At a quarter to ten you tell your family you’re going for a walk, pull on your jacket and head back downtown. The shops are shut, the streetlights are on, and your breath smokes in the cold November air. You get there with a few minutes to spare.`,
        },
        `Courthouse Square is nearly empty. Red is asleep on his bench by the bus stop, same as always. A couple strolls arm in arm toward the parking lot. Above everything, the clock tower’s hands point where they’ve pointed for thirty years: 10:04.`,
        `You find the lamppost on the corner and stand next to it, feeling ridiculous.`,
        `Then the air starts to hum.`,
        `It seems to come from everywhere at once, a deep electric note like a power line in the rain. Blue sparks crawl across the pavement. A wind picks up that doesn’t blow from any direction. You grab the lamppost.`,
        `Up on the tower, the stopped clock does something it hasn’t done in thirty years: the minute hand twitches.`,
        `There are three blinding flashes and a boom that knocks the breath out of you. Out of a ring of fire twenty feet away comes a steam locomotive. It’s flying, its wheels spinning on nothing and its headlamp sweeping the square. It settles onto the road with a hiss that sounds almost polite.`,
        `Then everything goes quiet. Not night quiet. Photograph quiet.`,
      ],
      choices: [{ text: `Continue`, to: 'S04' }],
    },
    {
      id: 'S04',
      title: 'Doc',
      era: '1985',
      time: 'NOV 12 1985 10:04 PM',
      cast: ['doc', 'player', 'train'],
      imagePrompt: `Doc Brown, goggles pushed up, holds a yellowed letter up to the headlamp of the steaming time train and stares at it in astonishment. The player stands beside him. Around them the square is frozen: a couple caught mid-step with one foot off the ground, a moth hanging motionless in the lamplight.`,
      text: [
        `A door in the side of the locomotive slides open, and a man in a long coat and goggles jumps down, waving a handheld device covered in blinking lights.`,
        `“Nobody move!” the man shouts. “Stay inside the field!”`,
        `Then he sees you. He stops dead and stares at you, and you stare back.`,
        `“Who are you?” he asks. “And why aren’t you frozen?”`,
        `You look around. The couple are frozen in mid-step, one foot off the ground. A moth hangs in the lamplight as if it’s been pinned there. Red’s snore has stopped halfway through. Nothing moves except you, the man, and a thin curl of steam from the locomotive’s stack.`,
        `Without a word, you hold out the letter.`,
        `He pushes up his goggles. It’s Doc Brown. You’ve seen him around town for years, usually running. He reads the letter once, then again, then holds it up to the headlamp.`,
        `“Great Scott,” he whispers. “That’s my handwriting. That’s my signature. But I’ve never written this letter in my life!” He looks at you over the top of the page. “Yet.”`,
        `Then he sees how you’re looking at the locomotive. “You’d better know now,” he says, “because it’s about to matter. That’s a time machine.” He jerks a thumb at the locomotive. “I built my first one out of a car. This one I built out of a train, in 1885. I’ve spent the last few weeks traveling in time with my family, and tonight my instruments picked up something very wrong with Hill Valley.”`,
        `He fastens a leather band with a small humming metal box on it around your wrist. “Chrono-field bracelet. You were standing inside the train’s field when time stopped. That’s the only reason you’re still moving. As long as you wear this, you stay in normal time, and anything you pick up will move for you. Don’t take it off. And don’t touch anyone. If you pull a frozen person into your field, they’ll wake up inside a moment that won’t let them out.”`,
        `He points at the clock tower. “At exactly 10:04, every clock in this town stopped, and time stopped with them. My instruments say it’s coming from up there.” He taps the letter. “And apparently we’re in this together.”`,
      ],
      choices: [
        { text: `Take a look around the square first`, to: 'S05' },
        { text: `Head straight for the clock tower`, to: 'S06' },
      ],
    },
    {
      id: 'S05',
      title: 'The Frozen Square',
      era: '1985',
      onEnter: { set: { sawTracks: true } },
      cast: ['doc', 'player'],
      imagePrompt: `Doc Brown crouches to peer at a string of water droplets frozen in mid-air under a gutter. A newspaper hangs mid-tumble over the road and a cat is frozen in mid-leap between trash cans. In the silvery frost on the grass, a line of glowing footprints leads toward the courthouse door.`,
      text: [
        `You walk into the square, and the square doesn’t notice.`,
        `Water from a leaking gutter hangs in a string of glassy beads. A newspaper that was blowing across the road is stuck in mid-tumble, headline up: COUNCIL DEBATES CLOCK TOWER’S FUTURE. A stray cat is frozen in mid-leap between two trash cans with a look of total commitment.`,
        `“Fascinating,” Doc says, crouching by the frozen water. “Time hasn’t slowed down. It’s stopped dead. Every atom in Hill Valley is holding its breath.”`,
        `Then you see the footprints.`,
        `There’s a thin frost on the grass of the square, frozen like everything else. Someone has walked across it, and the prints glow a faint, ghostly blue. They go out from the courthouse’s side door to the middle of the square, where they shuffle about as if someone stood there admiring the view. Then they go back again.`,
        `Doc looks at the prints, then at his own boots, then at yours.`,
        `“Those aren’t ours,” he says quietly. “And that glow means whoever made them walked here *after* everything stopped. Someone else is moving around in here.”`,
      ],
      choices: [{ text: `Follow the footprints`, to: 'S06' }],
    },
    {
      id: 'S06',
      title: 'The Side Door',
      era: '1985',
      cast: ['doc', 'player'],
      imagePrompt: `Close on the courthouse’s side door at night, its lock sliced cleanly through with a melted, blackened edge. Doc Brown examines the cut with a penlight while the player looks past him up a narrow wooden staircase spiraling into darkness.`,
      text: [
        { if: is('sawTracks'), text: `The glowing footprints lead straight back to the courthouse’s side door.` },
        `The side door of the courthouse, the one that leads up into the clock tower, is standing open. The lock hasn’t been picked. It’s been cut clean through, as if with something very hot, and the edges of the metal are blackened and cold.`,
        `Doc shines a penlight on it. “A thermal cutter. Nobody in 1985 owns one of those.”`,
        `Beyond the door, a narrow wooden staircase winds up into the dark. Somewhere above you, very faintly, something is ticking. It’s the only clock in Hill Valley that is.`,
      ],
      choices: [{ text: `Climb the stairs`, to: 'S07' }],
    },
    {
      id: 'S07',
      title: 'The Clock Room',
      era: '1985',
      cast: ['player', 'clamp'],
      imagePrompt: `Inside a cramped, dusty clock room full of giant iron gears. Moonlight glows through the back of an enormous translucent clock face, the hands in silhouette at 10:04. Bolted around the hands’ spindle is the chrono-clamp, its green screen glowing. The player reaches toward it.`,
      text: [
        `The stairs end in the clock room, a cramped space full of dust and the huge iron gears of the mechanism, which haven’t moved since 1955. Moonlight comes through the back of the enormous clock face, and you can see the hands in silhouette, stuck at 10:04.`,
        `Something has been bolted onto them.`,
        `It’s about the size of a toaster, made of brushed silver metal, and clamped around the spindle where the hands meet. Cables run from it into the old gears. A small screen on its side glows green. This is what’s ticking. Stamped into the casing are three letters: T.T.T.`,
        `The air around it wobbles like heat over a road. When you step closer, your bracelet starts to whine.`,
        `“Don’t—” Doc begins.`,
        `But it’s right there, held on with four ordinary-looking wing nuts. Whatever it is, it’s the thing freezing your town.`,
      ],
      choices: [
        { text: `Grab it and pull it off`, to: 'S08' },
        { text: `Step back and let Doc examine it`, to: 'S09' },
      ],
    },
    {
      id: 'S08',
      title: 'Pull',
      era: '1985',
      onEnter: { set: { pulledClamp: true } },
      cast: ['player', 'doc', 'clamp'],
      imagePrompt: `The player braces a foot against the gears and heaves at the chrono-clamp. Through the translucent clock face behind them, a jagged glowing crack splits the night sky over the town like breaking ice. Doc Brown lunges forward with an arm outstretched, shouting.`,
      text: [
        `You grab the device with both hands and heave.`,
        `It comes loose a quarter of an inch, and the whole world creaks.`,
        `It’s the sound a frozen lake makes just before it breaks, and it comes from everywhere: the stone walls, the moonlight, the inside of your own head. Through the glass of the clock face, you see a crack run across the sky over Hill Valley. Not a cloud. A crack, in the sky.`,
        `“STOP!” Doc shouts. “If that comes off by force, the moment it’s holding will shatter, and everyone in it!”`,
        `The device is warm and humming in your hands. One more pull and it’ll come free.`,
      ],
      choices: [
        { text: `Pull anyway. Better broken than frozen.`, to: 'E02' },
        { text: `Let go`, to: 'S09' },
      ],
    },
    {
      id: 'E02',
      title: 'Cracked',
      era: '1985',
      ending: { kind: 'bad' },
      cast: ['player', 'doc'],
      imagePrompt: `A surreal shattering: the clock room and the town beyond it break apart like a dropped mirror into hundreds of floating shards, each showing a different version of the town (rain, a shopping mall, an empty field). The player and Doc Brown stand at the center, clutching each other’s arms.`,
      text: [
        `You pull. The device comes free with a noise like the world’s biggest light bulb breaking.`,
        `Time doesn’t start again. It splinters. Through the clock face you watch Hill Valley break into a thousand glittering pieces, each one a slightly different town: one where it’s raining, one where the courthouse is a shopping mall, one where the clock tower was never built. Doc grabs your arm as the pieces spin apart like a dropped mirror.`,
        `When the light fades, you’re standing in a clock room that is also a parking garage and also an empty field, and Doc is saying “Great Scott” in three voices at once.`,
        `You spend a long time after that trying to find your way back to the one Hill Valley that was yours. You never quite manage it. Some things can’t be put back together.`,
      ],
    },
    {
      id: 'S09',
      title: 'Diagnosis',
      era: '1985',
      onEnter: { set: { clockStarted: true } },
      cast: ['doc', 'clamp'],
      imagePrompt: `Doc Brown kneels by the chrono-clamp examining it through a jeweler’s loupe, sketching a diagram of a brass cage on the back of an old letter. The clamp’s green screen shows a countdown. Iron gears and moonlight surround them.`,
      text: [
        { if: is('pulledClamp'), text: `The crack in the sky slowly seals itself, like ice skinning over a pond, and you remember to breathe.` },
        `Doc studies the device through a jeweler’s loupe, muttering to himself. After a long minute he sits back on his heels.`,
        `“It’s a chrono-clamp,” he says. “Technology from a long way past my time. It has pinned the tower’s hands at 10:04.”`,
        `He sees your face and explains. “Thirty years ago tonight, lightning struck this tower. My friend Marty was stranded in 1955 in my time machine, and that bolt was the only thing powerful enough to send him home. We ran a cable from this tower to the car and caught the lightning at 10:04 exactly. It worked. But it left a scar in time, right here. This tower is a weak point, and tonight is the thirtieth anniversary to the minute. Pin the tower and you pin the whole town.”`,
        `He taps the green screen. It shows a number, counting down: 5:59:58. 5:59:57.`,
        `“That’s how long until the clamp sets,” Doc says. “Six hours of our time, meaning time inside our fields. When it reaches zero, the freeze becomes permanent. Hill Valley stops at 10:04 PM on November 12th, 1985. Forever.”`,
        `“Can’t you just take it off?” you ask.`,
        `“Not by force,” Doc says. “It has to be released gently, with a Temporal Stabilizer.” He’s already sketching on the back of your letter. “Three parts. First, a flux-field regulator. I have one in my lab, right here in 1985. Second, a chronometric reference: a piece of this very clock from before any time traveler ever touched this town. That means 1885, before the clock was installed. Third, power. More than the train can spare, and more than anything in 1985 can produce. For that we’ll have to go forward. A century should do it.”`,
        `He synchronizes his wristwatch with the clamp’s screen.`,
        `A floorboard creaks on the stairs below you.`,
      ],
      choices: [{ text: `Continue`, to: 'S10' }],
    },
    {
      id: 'S10',
      title: 'The Figure on the Stairs',
      era: '1985',
      cast: ['rex'],
      imagePrompt: `Looking down a narrow spiral wooden staircase inside a clock tower: halfway down, caught in a shaft of moonlight from a slit window, a figure in a silver jumpsuit and a dark-visored helmet looks up, a chunky wrist device glowing electric blue. Tense, noir framing.`,
      text: [
        `You both freeze, which in this town is saying something.`,
        `Halfway down the stairs, caught in the moonlight from a narrow window, is a figure in a silver jumpsuit. It wears a helmet with a dark visor and has a chunky device strapped to its wrist that glows blue. It is not frozen, and it is looking straight at you.`,
        { if: is('sawTracks'), text: `“The footprints,” Doc whispers.` },
        `For a second nobody moves. Then the figure spins around and bolts down the stairs, three at a time.`,
      ],
      choices: [
        { text: `Chase them!`, to: 'S11' },
        { text: `Let them go. Get the regulator from Doc’s lab.`, to: 'S13' },
      ],
    },
    {
      id: 'S11',
      title: 'The Chase',
      era: '1985',
      onEnter: { set: { hasKeycard: true } },
      cast: ['player'],
      imagePrompt: `A frozen town square at night: the player sprints and lunges, fingers closing on empty air where a crackling burst of blue light is fading. A plastic keycard with a holographic clock-tower logo falls toward the wet pavement. A couple stands frozen mid-step in the background.`,
      text: [
        `You take the stairs so fast your feet barely touch them. Behind you, Doc is shouting something about not touching anyone.`,
        `The figure bursts through the courthouse door and out across the frozen square, weaving past the couple frozen in mid-step. You’re gaining on them. Ten feet. Five. You lunge, and your fingers close on a silver sleeve—`,
        `—and the figure slaps the device on its wrist. There’s a crack of blue light and a smell like a burned-out fuse, and your hand closes on nothing.`,
        `Something falls to the pavement where the figure was standing: a flat plastic card on a clip, still warm. One side has a hologram of a clock tower with a stylized T wrapped around it. The other side says:`,
        `**TANNEN TEMPORAL TOURS**<br>STAFF ACCESS · ALL AREAS<br>R. TANNEN`,
        `Doc arrives, gasping, reads it over your shoulder, and goes pale.`,
        `“Tannen,” he says. “Why is it always a Tannen?”`,
        `You know the name. Biff Tannen was the worst bully at Hill Valley High back in the fifties, and people say his family has been trouble in this town for as long as there’s been a town.`,
        `“Every generation,” Doc mutters. “Like clockwork.”`,
      ],
      choices: [{ text: `Pocket the card and head for Doc’s lab`, to: 'S13' }],
    },
    {
      id: 'S13',
      title: 'Doc’s Lab',
      era: '1985',
      cast: ['doc', 'player'],
      imagePrompt: `A cluttered garage laboratory at night: a wall covered in dozens of clocks, all stopped at 10:04; workbenches piled with gadgets under dust sheets. Doc Brown kneels at a squat iron safe beneath a workbench, hand on the dial, frowning, while the player holds a flashlight.`,
      text: [
        `The train carries you across town, low over the rooftops. Below you, Hill Valley looks like a model village: cars stopped at green lights, a dog frozen mid-bark in a front yard, lit windows with families frozen in front of their TVs. Doc sets down in the alley behind a garage on Riverside Drive.`,
        `Doc’s garage smells of engine oil and old solder. Dust sheets cover the workbenches. One wall is covered in clocks, dozens of them, and every one says 10:04.`,
        `“I left in a hurry a few weeks ago,” Doc says, not quite looking at you. “Things were… eventful.” He glances out of the window, toward the far side of town. “Marty’s out there somewhere, frozen in the middle of his evening. He helped me through every one of my time-travel disasters. Let’s not keep him waiting.”`,
        `He kneels by a squat iron safe under the workbench and puts his hand on the dial. Then he stops.`,
        `“The regulator’s in here,” he says. “Before I left, I changed the combination to the most important date of my life.” He frowns. “The trouble is, I have two of those.”`,
        `He holds up one finger. “November 5th, 1955: the day I slipped, hit my head, and dreamed up the flux capacitor, the part that makes time travel possible.” A second finger. “October 26th, 1985: the night of the first time-travel test, in the parking lot of the mall.”`,
        `He looks up at you. “You pick. I’ve been staring at this dial too long.”`,
      ],
      choices: [
        { text: `11-05-55: the day of the flux capacitor`, to: 'S14' },
        { text: `10-26-85: the night of the first test`, to: 'S13x' },
      ],
    },
    {
      id: 'S13x',
      title: 'Jammed',
      era: '1985',
      onEnter: { set: { safeJammed: true }, add: { delays: 1, minutes: -20 } },
      cast: ['doc', 'player'],
      imagePrompt: `Doc Brown levers at a stubborn iron safe with a crowbar, sweat on his brow, while the player holds a flashlight and a small fire extinguisher. A thin curl of smoke rises from the safe’s hinge. Clocks line the wall behind them.`,
      text: [
        `You spin the dial: 10, 26, 85. The handle doesn’t budge. Doc tries it again, harder. Something inside the lock goes *clunk*, and the dial spins loose in his fingers.`,
        `“Blast. The anti-tamper bolt.” He’s already reaching for a crowbar. “Hold the light.”`,
        `It takes twenty minutes of levering, muttering and one small fire before the door groans open.`,
        `Doc checks his watch and winces. “Twenty minutes we didn’t have. Let’s not make a habit of it.”`,
      ],
      choices: [{ text: `Continue`, to: 'S14' }],
    },
    {
      id: 'S14',
      title: 'The Plan',
      era: '1985',
      onEnter: { add: { minutes: -40 } },
      cast: ['doc', 'player', 'stabilizer'],
      imagePrompt: `Inside the wooden cab of the time train, lit by glowing instrument panels: Doc Brown bolts a copper-and-glass coil into an empty brass cage with two vacant sockets, one gear-shaped and one round. He hands the player a chunky 1980s walkie-talkie. Three rows of glowing time-circuit numbers shine above the controls.`,
      text: [
        {
          if: not(is('safeJammed')),
          text: `The dial clicks, the handle turns and the safe swings open. “The flux capacitor,” Doc says. “Of course. What was I thinking?”`,
        },
        `Inside the safe, wrapped in an oily cloth, is a coil of copper and glass the size of a soup can: the flux-field regulator.`,
        `Back in the train’s cab, Doc works fast. He bolts the regulator into a frame of brass and wire on the cab’s workbench, and the frame starts to look like a machine: a cage with two empty sockets. One is shaped like a gear. The other is a round slot that glows faintly, waiting for power.`,
        `“The chronometric reference goes here,” he says, tapping the gear-shaped socket. “The power source goes here.”`,
        `He hands you a walkie-talkie. “Wherever we go, keep this switched on. If we get separated, call me.”`,
        `Then he sets the time circuits: three rows of glowing numbers over the controls, showing where you’re going, where you are, and where you last left.`,
        `“Once the circuits are set, we get up to eighty-eight miles an hour,” he says. “At that speed, the time machine goes through time. Don’t ask me why it’s eighty-eight. It just is.”`,
        `“The clock’s ticking,” Doc says, tapping his watch. “Past or future first? Either way, we need both.”`,
      ],
      choices: [
        { text: `The past: Hill Valley, 1885`, to: 'S20' },
        { text: `The future: Hill Valley, 2085`, to: 'S30' },
      ],
    },

    // ── ACT 2A: 1885 ────────────────────────────────────────────
    {
      id: 'S20',
      title: 'Shonash Ravine',
      era: '1885',
      time: 'AUG 28 1885 09:12 PM',
      onEnter: { set: { visited1885: true }, add: { minutes: -20 } },
      cast: ['doc', 'player', 'train'],
      imagePrompt: `A moonlit desert ravine in 1885: the time train rests on the rocky floor, steam curling from it, hidden between tall canyon walls. Doc Brown stands by the cab holding a ridiculous false beard and a wide-brimmed hat, looking hopeful. The player looks toward the distant lamp-lights of a small frontier town.`,
      text: [
        `The train hits eighty-eight miles an hour and the night explodes into light.`,
        `When your eyes clear, the stars are brighter than you’ve ever seen them, and there’s no town below you. There’s only desert, silver in the moonlight, and a black gash in the ground ahead: a ravine, a couple of miles outside town. Doc brings the train down onto its floor, out of sight of anyone, with a hiss of steam.`,
        { if: is('visited2085'), text: `“After 2085,” Doc says, “I find this very relaxing.”` },
        `“August 28th, 1885,” Doc says, reading the display. “The courthouse clock came in by rail this afternoon. It’s in a crate at the depot, waiting for next week’s festival, when they’ll unveil it.”`,
        `He pulls off his goggles. “And I can’t go into town.”`,
        `“Why not?” you ask.`,
        `“Because I already live there,” Doc says. “A while back, by my own calendar, an accident stranded me in 1885 for most of a year, so I set up shop as the town blacksmith. Right now, as we speak, that slightly younger me is working in the blacksmith’s shop on Main Street. If he sees me, or anybody sees the two of us together… the consequences could be catastrophic.” He pauses and produces a false beard from his coat. “Of course, I could wear a disguise.”`,
      ],
      choices: [
        { text: `Go into town alone`, to: 'S21' },
        { text: `Let Doc come along in disguise`, to: 'S22' },
      ],
    },
    {
      id: 'S22',
      title: 'Disguise',
      era: '1885',
      cast: ['doc', 'player'],
      imagePrompt: `A dusty 1885 main street at night lit by oil lamps. Doc Brown, in a crooked false beard, an enormous wide-brimmed hat and an inside-out coat, stops dead beside the player in front of a blacksmith’s shop. Through its window, the red glow of a forge silhouettes a white-haired figure bent over an anvil.`,
      text: [
        `Doc’s disguise turns out to be a false beard, a hat with a very wide brim, and his coat turned inside out. He looks like a haystack that’s been in a fight.`,
        `You walk into Hill Valley together. It’s one dusty street, lit by oil lamps and one noisy saloon. Halfway along, a single building still has its lights on: a blacksmith’s shop. Through the window you can see the red glow of a forge and a white-haired figure bent over the anvil.`,
        `Doc stops dead. “There I am,” he whispers. “Look at my posture. Terrible.”`,
        `He takes a step toward the window. The window is very close, and it would only take a second to look.`,
      ],
      choices: [
        { text: `Sneak up to the window together for a quick look`, to: 'E03' },
        { text: `Grab his sleeve and hurry him past`, to: 'S21', set: { docTurnedBack: true } },
      ],
    },
    {
      id: 'E03',
      title: 'Double Doc',
      era: '1885',
      ending: { kind: 'bad' },
      cast: ['doc'],
      imagePrompt: `Through a grimy blacksmith’s-shop window, two identical white-haired Doc Browns stare at each other in shock: one inside holding a hammer by the forge, one outside with a false beard sliding off his chin. Both are beginning to keel over in a faint.`,
      text: [
        `You both lean in. Through the grimy glass, the Doc at the anvil looks up.`,
        `For one long second, two Emmett Browns stare at each other through a window: one holding a hammer, one with a beard sliding off his chin.`,
        `Then they both faint.`,
        `The blacksmith Doc wakes up first and starts asking questions. Where did his double come from? What is a time train? Who is this kid? Once he knows the answers, he can’t un-know them, and a man like Doc Brown doesn’t sit on answers like those. By the end of the week, he has built something in his shop that he shouldn’t build for years yet.`,
        `History bends, and then it buckles. Nothing you know about Hill Valley stays true for very long, and the two of you who came from that Hill Valley start to fade, like an old photograph left in the sun.`,
      ],
    },
    {
      id: 'S21',
      title: 'The Depot',
      era: '1885',
      cast: ['player'],
      imagePrompt: `An 1885 railway depot at night: a long wooden platform, a lamp glowing in the stationmaster’s window where a man dozes with his boots on the desk. At the far end, under a tarpaulin, stands a tall wooden crate. The player crouches in the shadows, sizing it up.`,
      text: [
        {
          if: is('docTurnedBack'),
          text: `Past the blacksmith’s, Doc stops, pulls off the beard and shakes his head. “This is madness. If he’d looked up… I’ll wait at the train. Call me if you need me.” He melts back into the dark.`,
          else: `Doc wishes you luck and stays with the train. “Call me if you need me,” he says, tapping your walkie-talkie. You climb out of the ravine and follow the railroad tracks toward the lights. Hill Valley in 1885 is one dusty main street lit by oil lamps. Piano music spills out of a saloon, and horses doze at a hitching rail. At the end of the street is the courthouse, still being built, wrapped in wooden scaffolding. There’s a square hole at the top where a clock is meant to go.`,
        },
        `The railway depot is a long wooden platform where the tracks meet the edge of town. A lamp burns in the stationmaster’s window, and inside, the stationmaster is asleep in his chair with his boots on the desk.`,
        `At the end of the platform, under a tarpaulin, is a crate as tall as you are. Stenciled on its side: FRAGILE · CLOCK MECHANISM · HILL VALLEY COURTHOUSE.`,
        `You could creep round the back of the platform and get to the crate without waking anyone. Or you could knock and talk your way in. A stationmaster who opens the crate for you won’t be shouting “thief” later.`,
      ],
      choices: [
        { text: `Sneak around the back`, to: 'S23' },
        { text: `Wake the stationmaster and talk your way in`, to: 'S24' },
      ],
    },
    {
      id: 'S24',
      title: 'Riders',
      era: '1885',
      onEnter: { set: { metTannen: true } },
      cast: ['madDog', 'player'],
      imagePrompt: `Four menacing outlaws on horseback rein in at a lamplit 1885 depot platform, the leader Mad Dog Tannen leaning down from his saddle. A terrified stationmaster cowers in the doorway. Behind them a wanted poster is nailed to the wall. The player stands half in shadow at the platform’s end.`,
      text: [
        `You knock. The stationmaster wakes with a snort, blinks at your clothes, and is halfway through saying “What in tarnation—” when hooves thunder up to the platform.`,
        `There are four riders. The one in front wears a long duster and a hat pulled low, and he has exactly the kind of face you’d expect to see on a wanted poster. In fact, it *is* on a wanted poster, nailed to the depot wall behind him.`,
        `BUFORD “MAD DOG” TANNEN.`,
        `“Evenin’,” he says to the stationmaster, who has gone the color of milk. “Heard there’s a strongbox comin’ through on tomorrow’s train. I’d like to know which car.”`,
        `Nobody has noticed you yet. The shadows at the end of the platform are very close.`,
      ],
      choices: [
        { text: `Slip into the shadows and around the back`, to: 'S23' },
        { text: `Step forward before he hurts the stationmaster`, to: 'S27' },
      ],
    },
    {
      id: 'S27',
      title: 'Mad Dog',
      era: '1885',
      cast: ['madDog', 'player'],
      imagePrompt: `Mad Dog Tannen, spurs jingling, swaggers across a lamplit wooden platform toward the player, sneering down at their sneakers and bomber jacket. His gang watches from their horses. Tense western standoff framing.`,
      text: [
        `“Leave him alone,” you hear yourself say.`,
        `Four heads turn. Mad Dog Tannen looks at your sneakers, your jeans and your jacket, and grins a grin with a lot of gaps in it.`,
        `“Well, lookee here. What in the Sam Hill are you s’posed to be?”`,
        `He swings down from his horse and walks toward you, spurs jingling. The stationmaster takes the chance to dive under his desk.`,
        `Tannen stops right in front of you. “I asked you a question, runt.”`,
      ],
      choices: [
        {
          text: `Tell him the strongbox already left on this afternoon’s eastbound freight`,
          to: 'S23',
          set: { fooledTannen: true },
        },
        { text: `Tell him to back off`, to: 'S28' },
      ],
    },
    {
      id: 'S28',
      title: 'The Palace Saloon',
      era: '1885',
      time: 'AUG 28 1885 10:05 PM',
      cast: ['madDog', 'player'],
      imagePrompt: `A rowdy 1885 saloon interior lit by oil lamps: the player sits tied to a wooden post on the sawdust floor. At a nearby card table, Mad Dog Tannen holds a 1980s walkie-talkie up to his ear with a puzzled scowl while his gang plays poker.`,
      text: [
        `Telling Mad Dog Tannen to back off works about as well as you’d expect.`,
        `Ten minutes later you’re sitting on the floor of the Palace Saloon, tied to a post with a rope that smells of horse. Tannen’s gang is playing cards at the next table. Tannen himself has your walkie-talkie and is shaking it next to his ear.`,
        `“Ain’t never seen nothin’ like this,” he says. “You a Pinkerton? Some kinda spy?”`,
        `He tosses it back onto the table, just out of reach. If you can get a hand free, you might be able to reach it.`,
        `“I’ll tell you what,” Tannen says. “I’ll let you go if you give me somethin’ worth lettin’ you go for.”`,
        `You think of the train sitting in the ravine: solid iron, and worth more than everything else in this town put together.`,
      ],
      choices: [
        { text: `Work a hand free and quietly radio Doc`, to: 'S29' },
        { text: `Tell Tannen about the “iron horse” in the ravine`, to: 'E04' },
      ],
    },
    {
      id: 'S29',
      title: 'Rescue',
      era: '1885',
      time: 'AUG 28 1885 10:25 PM',
      onEnter: { set: { rescued: true }, add: { delays: 1, minutes: -20 } },
      cast: ['doc', 'player'],
      imagePrompt: `Chaos in an 1885 saloon filled with thick white smoke: chairs toppling, outlaws coughing and flailing. Doc Brown, in a crooked false beard and a huge hat, cuts the player free from a post with a pocketknife. A smoking metal canister rolls across the floor.`,
      text: [
        `It takes forever to twist one hand free, and forever again to hook the walkie-talkie off the table with your foot while the gang argues over cards. You whisper into it and hope.`,
        `Twenty long minutes later, the saloon doors swing open, and something the size of a cannonball rolls across the floor, hissing.`,
        `The room fills with thick white smoke. Men shout. Chairs go over. Someone in a very wide-brimmed hat and a crooked beard cuts your ropes with a pocketknife and hauls you out of the back door by your collar.`,
        `“Emergency smoke canister,” Doc pants as you run. “Standard equipment. Nobody saw my face. I hope.” He points you toward the depot. “Get the part. I’ll be at the train!”`,
        `He vanishes into the dark.`,
      ],
      choices: [{ text: `Run for the depot`, to: 'S23' }],
    },
    {
      id: 'E04',
      title: 'Stuck in 1885',
      era: '1885',
      ending: { kind: 'bad' },
      cast: ['doc', 'player', 'train'],
      imagePrompt: `Dawn in a desert ravine: the time train lies tilted and broken on the rocks, pipes torn, steam wisping from its wounds. Doc Brown and the player sit on a boulder beside it, dusty and defeated, watching a gang of riders disappear over the ridge.`,
      text: [
        `Tannen’s eyes light up when you describe the train. By midnight his whole gang is riding for the ravine, with you slung over a saddle like a sack of flour.`,
        `Doc sees them coming and does the only thing he can: he fires up the train to get it out of their reach. But Tannen’s men are already swarming over the cab, hacking at pipes and wires they don’t understand. The train lurches up, spits sparks, and comes down hard on the floor of the ravine. Something inside it breaks with a sound you feel in your teeth.`,
        `The gang rides away in disgust, because you can’t sell an iron horse that won’t run, and leaves you and Doc sitting in the wreckage.`,
        `“I can fix it,” Doc says. “Give me time.” But the parts he needs won’t be invented for fifty years, and somewhere a century away, a clamp on a clock tower is counting down to zero.`,
        `You open a clock repair shop on Main Street. Doc lives in a cabin out past the ravine and grows a real beard. Your clocks are the most accurate in the territory. You make sure of it.`,
      ],
    },
    {
      id: 'S23',
      title: 'The Crate',
      era: '1885',
      cast: ['player'],
      imagePrompt: `By lantern light, the player kneels inside an opened wooden crate packed with straw, where a gleaming new brass clock mechanism rests. In one hand they hold a small velvet-lined wooden box containing a toothed brass wheel. An identical wheel is mounted inside the mechanism, with a paper tag tied to it.`,
      text: [
        { if: is('rescued'), text: `Behind you, the saloon is still coughing. You reach the depot unseen.` },
        {
          if: is('fooledTannen'),
          text: `Tannen spits in the dust, and he and his gang wheel their horses around and gallop off east in a cloud of dust, cursing. The stationmaster doesn’t come out from under his desk. You can’t blame him.`,
        },
        {
          if: all(is('metTannen'), not(is('fooledTannen')), not(is('rescued'))),
          text: `While Tannen leans over the stationmaster’s desk making threats, you slip off the end of the platform and around the back. Nobody sees you go. A few minutes later you hear the gang ride off, still arguing.`,
        },
        {
          if: not(is('metTannen')),
          text: `You creep round the back of the depot, under the edge of the platform, and come up beside the crate. You can hear snoring from the stationmaster’s window.`,
        },
        `The crate’s lid is only held down with a few nails, and you work them loose. Packed in straw is the clock mechanism for the Hill Valley courthouse: a great gleaming nest of brass wheels. It’s the same machine that stands silent in the tower in 1985, only here it’s new and clean and has never been stopped by lightning.`,
        `There’s the escapement wheel, the toothed wheel at the heart of the clock that makes it tick, mounted in place and shining. A paper tag hangs from it: TESTED & TRUE · J. HARDY, CLOCKMAKER, ST. LOUIS.`,
        `Beside the mechanism, tucked into the straw, is a small wooden box. Inside, wrapped in velvet, is a second escapement wheel identical to the first. A label in copperplate handwriting says SPARE.`,
        `Two wheels. Something about that tickles the back of your mind.`,
      ],
      choices: [
        { text: `Take the mounted wheel, the one that’s actually part of the clock`, to: 'S25' },
        { text: `Take the spare`, to: 'S26' },
      ],
    },
    {
      id: 'S25',
      title: 'Tested and True',
      era: '1885',
      onEnter: { set: { escapement: 'original', lastEra: '1885' }, add: { minutes: -90 } },
      cast: ['doc', 'stabilizer'],
      imagePrompt: `Inside the lantern-lit time-train cab in a dark ravine, Doc Brown turns a gleaming brass clock wheel over in his fingers with a faintly uneasy expression, about to fit it into the brass stabilizer cage on his workbench.`,
      text: [
        `It takes a screwdriver and some nerve, but the mounted wheel comes out. You nail the crate shut again. Nobody will know it’s missing until they try to make the clock tick.`,
        `Back at the ravine, Doc turns the wheel over in the lantern light. “Hm,” he says. Just “hm.” Then he fits it into the stabilizer’s gear-shaped socket, where it sits perfectly.`,
        {
          if: is('fooledTannen'),
          text: `You tell him about Tannen and the eastbound freight. He snorts. “Tannen robs somebody every other week. One wasted ride won’t make the history books.”`,
        },
        { if: is('visited2085'), text: `“That’s the last part,” he says.`, else: `“Next stop, 2085,” he says. “By way of home.”` },
        `He throws the train into gear. The walls of the ravine streak past, and the numbers on the display roll forward a hundred years.`,
      ],
      choices: [{ text: `Continue`, to: 'S40' }],
    },
    {
      id: 'S26',
      title: 'The Spare',
      era: '1885',
      onEnter: { set: { escapement: 'spare', lastEra: '1885' }, add: { minutes: -90 } },
      cast: ['doc', 'stabilizer'],
      imagePrompt: `Inside the lantern-lit time-train cab in a dark ravine, Doc Brown beams with delight as he holds a gleaming brass clock wheel up to the lantern, the brass stabilizer cage waiting on the workbench beside him.`,
      text: [
        `You close the little box and tuck the spare wheel inside your jacket. You leave the clock itself exactly as you found it and nail the crate shut again.`,
        `Back at the ravine, Doc holds the wheel up to the lantern and beams.`,
        `“The spare!” he says. “Brilliant. It’s part of the same clock, cut by the same hands from the same brass, and it has never been used. The mounted one has to be in that clock when they unveil it next week. If it weren’t…” He shudders. “Let’s not think about that.”`,
        {
          if: is('fooledTannen'),
          text: `You tell him about Tannen and the eastbound freight. He snorts. “Tannen robs somebody every other week. One wasted ride won’t make the history books.”`,
        },
        { if: is('visited2085'), text: `He fits the wheel into its socket. “That’s the last part.”`, else: `He fits the wheel into its socket. “Next stop, 2085. By way of home.”` },
        `He throws the train into gear. The walls of the ravine streak past, and the numbers on the display roll forward a hundred years.`,
      ],
      choices: [{ text: `Continue`, to: 'S40' }],
    },
    {
      id: 'S26b',
      title: 'The Swap',
      era: '1885',
      time: 'AUG 28 1885 11:40 PM',
      onEnter: { set: { escapement: 'spare', lastEra: '1885' }, add: { delays: 1, minutes: -20 } },
      cast: ['player'],
      imagePrompt: `Night at the 1885 depot: the player, their hands visibly translucent and fading, fits a brass wheel back into the clock mechanism in the straw-filled crate by moonlight, a velvet box open beside them.`,
      text: [
        `Doc takes the train back to the ravine an hour after you first left it, in case your earlier self is still wandering around.`,
        `You run to the depot in the dark. The stationmaster’s lamp is out. The crate is exactly as you left it. You pry up the lid, fit the mounted wheel back into place with fingers that are slowly turning see-through, and take the spare from its velvet box instead.`,
        `The moment the mounted wheel clicks home, the feeling comes back into your hands.`,
        `Back at the train, Doc fits the spare into the stabilizer and checks his watch. “Twenty minutes. Expensive, but cheaper than never having existed.”`,
      ],
      choices: [{ text: `Back to 1985`, to: 'S40' }],
    },

    // ── ACT 2B: 2085 ────────────────────────────────────────────
    {
      id: 'S30',
      title: 'Hill Valley, 2085',
      era: '2085',
      time: 'NOV 12 2085 07:30 PM',
      onEnter: { set: { visited2085: true }, add: { minutes: -20 } },
      cast: ['doc', 'player', 'train'],
      imagePrompt: `The time train flies through a neon 2085 skyline of glass towers and glowing lanes of flying cars. Below, a historic clock tower is enclosed in a sweeping building of curved glass and light topped by a giant glowing hologram of a frozen clock face. A police drone with blinking lights flies alongside the cab. Doc Brown leans out of the cab, aghast.`,
      text: [
        `The train breaks through into the future at eighty-eight miles an hour and keeps flying, because in 2085 there’s traffic up here.`,
        `“November 12th, 2085,” Doc reads off the display. “A hundred years to the night.” Flying cars stream past in glowing lanes. Glass towers rise where the old neighborhoods used to be.`,
        { if: is('visited1885'), text: `After the dust of 1885, it’s like being dropped into a pinball machine.` },
        `In the middle of it all, right where it belongs, is the courthouse. The clock tower is still standing. But it has been wrapped inside a building of curved glass and light, under a sign a hundred feet tall:`,
        `**TANNEN TEMPORAL TOURS PRESENTS: THE FROZEN MOMENT**<br>Walk through Hill Valley, frozen forever at 10:04 PM, Nov. 12, 1985!`,
        `Doc makes a noise like a kettle. “He’s turned our town into a museum!”`,
        `A police drone pulls up alongside the cab and blinks its lights at you. Doc waves at it nervously. “I’d better keep the train moving before it asks for my license. You go. Find us a power source. The future runs on chrono-cells, and we need one. Keep your walkie-talkie on.”`,
        `He drops you on a landing platform by the plaza.`,
      ],
      choices: [
        { text: `Go into the Frozen Moment`, to: 'S31' },
        { text: `Look for a shop that sells chrono-cells`, to: 'S32' },
        { text: `Find the staff entrance and try R. Tannen’s keycard`, to: 'S33', if: is('hasKeycard') },
      ],
    },
    {
      id: 'S31',
      title: 'The Frozen Moment',
      era: '2085',
      onEnter: { set: { sawExhibit: true } },
      cast: ['player'],
      imagePrompt: `Inside a dim, eerie museum: a perfect full-scale replica of a 1985 town square at night, with frozen figures mid-step. Futuristic tourists in shiny clothes take pictures. In the foreground, the player stands stunned before an exhibit of a steam locomotive with two frozen figures beside it: a white-haired man in a long coat and a teenager in a bomber jacket.`,
      text: [
        `You join a line of tourists at the entrance. A turnstile scans you and waves you through under a sign reading FIRST VISIT FREE · GIFT SHOP AT EXIT. Inside, it’s cold and dim and uncanny. It’s Courthouse Square, the one you just left, reproduced down to the last detail: the couple in mid-step, Red on his bench. A soft voice explains that you’re walking through a perfect scan of the real thing, taken by the very device that froze it, and that the real Hill Valley is still out there in 1985, stopped forever.`,
        `Tourists in shiny clothes wander through, taking pictures.`,
        `Then you turn a corner and stop dead.`,
        `There’s a steam locomotive in the middle of the square. Standing beside it, frozen in place, are a white-haired man in a long coat and a teenager in a bomber jacket with a walkie-talkie. The teenager is you. The plaque reads: MYSTERY VISITORS. Scanned at the moment the freeze became permanent. Identity unknown.`,
        `Your walkie-talkie crackles. “Everything all right?” Doc asks. “You’ve gone very quiet.”`,
        `You tell him. There’s a long pause.`,
        `“That’s the future as it stands right now,” he says at last. “It isn’t written yet. Every choice we make changes it.”`,
        `On the way out, past the gift shop, hangs a portrait of a smiling man in a silver jumpsuit. FOUNDER: REX TANNEN, who discovered the Frozen Moment and brought it to the world.`,
      ],
      choices: [
        { text: `Find a shop that sells chrono-cells`, to: 'S32' },
        { text: `Find the control room. There has to be one.`, to: 'S34' },
        { text: `Use R. Tannen’s keycard on the staff door by the gift shop`, to: 'S33', if: is('hasKeycard') },
      ],
    },
    {
      id: 'S32',
      title: 'Wilson’s Power Plus',
      era: '2085',
      cast: ['player'],
      imagePrompt: `A narrow, cluttered futuristic shop crammed with glowing gadgets; shelves of palm-sized cylinders pulsing soft blue. Behind the counter an elderly shopkeeper with a magnifying visor stares in awe at the Walkman with orange-foam headphones hanging around the player’s neck. A framed vintage photo of a smiling 1980s politician hangs on the wall.`,
      text: [
        `You find it on a side street off the plaza: a narrow shop squeezed between two towers, crammed with glowing things. A sign reads WILSON’S POWER PLUS · POWERING HILL VALLEY SINCE 2031. Beneath it hangs a framed photo of a smiling man in a 1980s suit, captioned OUR FOUNDER’S GREAT-GRANDFATHER, MAYOR GOLDIE WILSON.`,
        `Behind the counter are chrono-cells: palm-sized cylinders that pulse blue like slow heartbeats. The price tag on the smallest one says 4,000 credits.`,
        `You don’t have any credits. You have a dollar forty in change, a house key and your Walkman.`,
        `The shopkeeper is an old woman in a magnifying visor, and she’s staring at your Walkman as if it were a crown jewel.`,
        `“Is that… a genuine 1980s portable cassette player?” she asks. “With the orange foam headphones?” She takes a shaky breath. “Does it *work*?”`,
      ],
      choices: [
        { text: `Offer her the Walkman for a chrono-cell`, to: 'S35' },
        { text: `Wait until she’s distracted and grab a cell`, to: 'S36', set: { caughtAt: 'shop' } },
      ],
    },
    {
      id: 'S33',
      title: 'Staff Only',
      era: '2085',
      cast: ['player'],
      imagePrompt: `A futuristic control room humming with holographic screens showing museum exhibits; one wall is a rack of dozens of glowing blue cylinders. The player stands at the main console reading a glowing log display with a shocked expression, a keycard in hand. Through a window, across a plaza, a sober government office glows.`,
      text: [
        `Around the side of the Frozen Moment building, past the gift shop windows, is a smooth grey door marked STAFF. You hold the keycard up to it, and it blinks green. Somebody hasn’t reported a lost card.`,
        `Behind it is a control room humming with screens. Most of them show the Frozen Moment’s exhibits. One whole wall is a rack of chrono-cells, dozens of them, powering the attraction.`,
        `On the main console, a log is open:`,
        `UNREGISTERED JUMP · R. TANNEN<br>DESTINATION: HILL VALLEY, NOV 12 1985, 09:51 PM<br>PAYLOAD: CHRONO-CLAMP (EXPERIMENTAL)<br>STATUS: SUCCESS · PROJECTED ANNUAL REVENUE: 40,000,000 CR`,
        `Rex Tannen didn’t discover the Frozen Moment. He made it.`,
        `The console has a slot that will spit out a data chip if you press the button marked EXPORT. Through the window, right across the plaza, you can see a sign: TEMPORAL AUTHORITY · HILL VALLEY BRANCH.`,
      ],
      choices: [
        { text: `Export the log and take it to the Temporal Authority`, to: 'S38' },
        { text: `Forget the log. Grab a cell off the rack and run.`, to: 'S36', set: { caughtAt: 'rack' } },
      ],
    },
    {
      id: 'S34',
      title: 'Authorized Staff Only',
      era: '2085',
      cast: ['player'],
      imagePrompt: `A cramped service corridor full of cables and humming machinery behind a museum. A smooth white security robot with a single large red eye glides out of an alcove and bathes the player in a soft blue beam, stopping them mid-step three paces from a door.`,
      text: [
        `Every building has a back way in. This one’s is a service corridor behind the exhibits, full of cables and humming machinery, leading to a door marked CONTROL · AUTHORIZED STAFF ONLY.`,
        `You’re three steps from the door when a smooth white robot glides out of an alcove. It has one large eye, and the eye turns red.`,
        `“UNAUTHORIZED VISITOR,” it says pleasantly. “PLEASE HOLD STILL. MR. TANNEN HAS BEEN NOTIFIED.”`,
        `A soft blue beam washes over you, and your legs stop working.`,
      ],
      choices: [{ text: `Continue`, to: 'S36', set: { caughtAt: 'corridor' } }],
    },
    {
      id: 'S36',
      title: 'Rex Tannen',
      era: '2085',
      onEnter: { set: { tannenKnows: true } },
      cast: ['rex', 'player'],
      imagePrompt: `A sleek penthouse office under a glass dome at night, the spire of an old clock tower visible through the glass. Rex Tannen leans back smugly behind a glossy desk with a charging rack of glowing blue cylinders on it. The player stands before him flanked by white security robots, a walkie-talkie clipped to their belt.`,
      text: [
        {
          if: is('caughtAt', 'shop'),
          text: `The shopkeeper’s security drone is faster than you. Two minutes later, officers from Tannen Temporal Security (which, it turns out, is Hill Valley’s official security contractor) march you across the plaza, into an elevator…`,
        },
        {
          if: is('caughtAt', 'corridor'),
          text: `The robot floats you, stiff as a plank, into an elevator…`,
        },
        {
          if: is('caughtAt', 'rack'),
          text: `Your hand is on a cell when the alarms go off. The door locks. Two security robots glide in and escort you into an elevator…`,
        },
        `…and up to an office at the very top of the building, under a glass dome. Through the glass you can see the spire of the clock tower.`,
        `Behind a desk sits the man from the portrait, silver jumpsuit and all.`,
        `“You,” says Rex Tannen. “The kid on the stairs.”`,
        { if: is('hasKeycard'), text: `He spots the keycard clipped to your jacket and snatches it back. “And I’ll take that.”` },
        `He leans back. “You and that old man have been a real headache. Do you know what that frozen town is worth? Every school on the planet sends its kids to see it. It’s the only genuine frozen moment in history, and I’m the only one who knows how it got there.”`,
        `He smiles. “So I’m going to put you in it. In the new wing. A living exhibit: ‘Time Traveler, Circa 1985.’ You’ll be a sensation.”`,
        `On his desk, in a charging rack, sit six chrono-cells. Your walkie-talkie is still clipped to your belt.`,
      ],
      choices: [
        { text: `Hit the walkie-talkie’s call button and yell for Doc`, to: 'S37' },
        { text: `Tell him the Temporal Authority is on its way`, to: 'E06' },
      ],
    },
    {
      id: 'E06',
      title: 'Exhibit A',
      era: '2085',
      ending: { kind: 'bad' },
      cast: ['player'],
      imagePrompt: `A futuristic museum wing: the player stands perfectly still inside a shimmering column of blue light on a pedestal, one hand frozen halfway to a walkie-talkie. Tourists in shiny clothes crowd around and take pictures. A glowing plaque sits at the base.`,
      text: [
        `“The Temporal Authority is on its way,” you say. “I told them everything.”`,
        `Rex studies your face for a long moment. Then he laughs. “No, you didn’t. If you had, they’d be here already. And you wouldn’t be sweating.”`,
        `He presses a button on his desk.`,
        `The new wing of the Frozen Moment opens a month later. The star exhibit is a teenager in 1980s clothes, standing perfectly still in a shimmering column of blue light, one hand halfway to a walkie-talkie. Visitors say it looks so real.`,
        `Somewhere above the city, a steam train circles for a very long time, then disappears.`,
      ],
    },
    {
      id: 'S37',
      title: 'Through the Roof',
      era: '2085',
      onEnter: { set: { hasCell: true, lastEra: '2085' }, add: { delays: 1, minutes: -110 } },
      cast: ['train', 'doc', 'player', 'rex'],
      imagePrompt: `Explosive action: the time train bursts through a glass-domed penthouse ceiling in a shower of glittering shards and steam, wheels spinning. Doc Brown leans out of the cab, arm outstretched, as the player leaps for his hand clutching a glowing blue cylinder. Rex Tannen dives behind his desk.`,
      text: [
        `“DOC!” you yell. “TOP OF THE TOWER! GLASS ROOF!”`,
        `Tannen lunges for the walkie-talkie. He’s too slow, and the train is faster.`,
        `It comes through the dome in a shower of glass and steam, whistle screaming, and hangs over the desk with its wheels spinning. Doc leans out of the cab and holds out his hand.`,
        `You snatch a chrono-cell from the charging rack, then grab Doc’s hand, and he hauls you into the cab as Tannen shouts something that’s lost in the steam.`,
        `“A class-seven chrono-cell!” Doc says as the city drops away beneath you. “Well done! Although I’m fairly sure we’ve made an enemy.”`,
        `He slots the cell into the stabilizer. His watch beeps. The chase has cost you twenty minutes you didn’t have.`,
      ],
      choices: [{ text: `Back to 1985`, to: 'S40' }],
    },
    {
      id: 'S35',
      title: 'A Fair Trade',
      era: '2085',
      onEnter: { set: { hasCell: true, lastEra: '2085' }, add: { minutes: -90 } },
      cast: ['doc', 'player', 'train'],
      imagePrompt: `On a neon-lit landing platform high above a futuristic city, Doc Brown gazes rapturously at a glowing blue cylinder cupped in the player’s hands, the time train hovering beside them with its cab door open.`,
      text: [
        `She gives you a chrono-cell, the biggest one in the shop, and throws in a carry case. She holds your Walkman in both hands as if it were a baby bird.`,
        `“Nobody has seen one of these working in fifty years,” she says. “You have no idea what you’ve done for me.”`,
        `You call Doc. The train swoops down to the landing platform outside, and Doc gazes at the cell exactly the way she gazed at the Walkman.`,
        `“A class-seven chrono-cell,” he breathes. “More power in the palm of your hand than a hundred bolts of lightning!” He slots it into the stabilizer, where it glows steadily.`,
        { if: is('visited1885'), text: `“That’s the last part,” he says.`, else: `“Next stop, 1885,” he says. “By way of home.”` },
      ],
      choices: [{ text: `Back to 1985`, to: 'S40' }],
    },
    {
      id: 'S38',
      title: 'The Temporal Authority',
      era: '2085',
      onEnter: { set: { authorityAlerted: true, hasCell: true, lastEra: '2085' }, add: { minutes: -90 } },
      cast: ['player'],
      imagePrompt: `A calm, minimalist futuristic government office with an hourglass emblem on the wall. A composed officer in a grey uniform places a glowing blue cylinder in the player’s hands across a desk, a data chip plugged into a holographic display between them.`,
      text: [
        `The Temporal Authority’s Hill Valley branch is a quiet office with a sign that reads TIME IS EVERYONE’S RESPONSIBILITY. The officer on duty listens to your story with a polite, patient face, the face of someone who has heard a lot of stories. Then she plugs in the data chip, and her face changes.`,
        `“An unregistered jump,” she says slowly. “An experimental clamp. On a populated town.” She presses a button on her desk. “Get me a response team.”`,
        `She turns back to you. “Tannen can afford a lot of lawyers. If we want this to stick, we catch him in the act. The next time he makes an unregistered jump, we’ll be right behind him. You’re going back there, aren’t you?”`,
        `You nod.`,
        `She takes a chrono-cell out of a cabinet and puts it in your hands. “Evidence locker. Confiscated from a smuggler last week. Consider it a loan.”`,
        `Her eyes flick over your jacket, your jeans, your walkie-talkie. “And I’m not going to ask how *you* got here,” she says. “Go.”`,
        `Doc picks you up at the plaza and slots the cell into the stabilizer, grinning. “Allies! In the future! How refreshing.”`,
      ],
      choices: [{ text: `Back to 1985`, to: 'S40' }],
    },

    // ── HUB AND FINALE: 1985 ────────────────────────────────────
    {
      id: 'S40',
      title: 'The Frozen Square',
      era: '1985',
      time: 'NOV 12 1985 10:04 PM',
      cast: ['doc', 'player', 'train'],
      imagePrompt: `The time train settles back into the frozen night-time courthouse square, steam curling. Doc Brown and the player step down from the cab and look up at the clock tower. Everything around them is perfectly still: the couple mid-step, the newspaper mid-air.`,
      text: [
        {
          if: is('lastEra', '1885'),
          text: `The desert and the stars vanish, and the train drops into Courthouse Square, where it is still 10:04 PM and nothing has moved.`,
          else: `The towers of 2085 vanish, and the train drops into Courthouse Square, where it is still 10:04 PM and nothing has moved.`,
        },
        `It’s exactly as you left it. The couple still has one foot in the air. Red is still halfway through his snore. The moth still hangs in the lamplight by your lamppost.`,
        { if: not(is('escapement', 'original')), text: `Above it all, the clamp’s faint green glow shows through the clock face.` },
        { if: is('escapement', 'spare'), text: `In the cab, the stabilizer’s gear-shaped socket holds the spare escapement wheel from 1885.` },
        { if: is('escapement', 'none'), text: `The stabilizer’s gear-shaped socket is still empty. That part is waiting in 1885.` },
        { if: is('hasCell'), text: `The chrono-cell from 2085 glows steadily in its slot.`, else: `The power slot is still dark. That part is waiting in 2085.` },
        {
          if: is('escapement', 'original'),
          text: `You climb down from the cab, look up at the clock tower, and your stomach drops. The clock face is blank. No numbers, no hands, just a pale, empty circle, as if there had never been a clock there at all.`,
        },
        {
          if: is('escapement', 'original'),
          text: `Doc’s face is grey. “The clock never ran,” he says. “Without that wheel it never ticked once, not in 1885 and not in 1955. And if it was never running, it never stopped at 10:04 when the lightning hit. That stopped clock is how we knew, to the second, when the lightning would strike. Without it, Marty never made it home from 1955. I never built the train. We never came here. None of this…” He looks down at his hands. So do you. You can see the cobblestones through your fingers.`,
        },
        {
          if: all(complete, { flag: 'delays', is: 0 }),
          text: `Doc checks his watch and nods. “Assembly takes seventy-nine minutes. That leaves us twenty-one to spare. Plenty!” He doesn’t sound as though he thinks it’s plenty.`,
        },
        {
          if: all(complete, { flag: 'delays', is: 1 }),
          text: `Doc checks his watch and does some sums in the air with one finger. “Assembly takes seventy-nine minutes,” he says. “We have eighty. We’ll have exactly one minute to spare.”`,
        },
        {
          if: all(complete, { flag: 'delays', gte: 2 }),
          text: `Doc looks at his watch for a long time. “Assembly takes seventy-nine minutes,” he says quietly. “I’ve done the arithmetic. We have less than that.” He doesn’t say anything else. He doesn’t need to.`,
        },
        {
          if: all(not(complete), not(is('escapement', 'original')), { flag: 'delays', is: 0 }),
          text: `Doc checks his watch. “Right on schedule. Let’s keep it that way.”`,
        },
        {
          if: all(not(complete), not(is('escapement', 'original')), { flag: 'delays', gte: 1 }),
          text: `Doc checks his watch and frowns. “We’re behind. No more detours.”`,
        },
      ],
      choices: [
        { text: `Go back to 1885 right now and put that wheel back`, to: 'S26b', if: is('escapement', 'original') },
        { text: `There’s no time. Build the stabilizer anyway.`, to: 'E05', if: is('escapement', 'original') },
        { text: `Set the circuits for 1885`, to: 'S20', if: is('escapement', 'none') },
        { text: `Set the circuits for 2085`, to: 'S30', if: all(is('escapement', 'spare'), not(is('hasCell'))) },
        { text: `Build the stabilizer and climb the tower`, to: 'S41', if: complete },
      ],
    },
    {
      id: 'E05',
      title: 'Paradox',
      era: '1985',
      ending: { kind: 'bad' },
      cast: ['doc', 'player', 'train'],
      imagePrompt: `In the frozen night square, Doc Brown and the player fade away like breath on a mirror, their bodies translucent, the brass stabilizer slipping through the player’s ghostly fingers. Behind them the clock tower shows a blank, empty face.`,
      text: [
        `“We’ll install the stabilizer first,” you say, “and fix the wheel afterwards.”`,
        `Doc opens his mouth to argue, and you can see the back of the cab through it.`,
        `It happens faster than you expected. The stabilizer slips through your fingers, because your fingers aren’t really there any more. The train fades around you like breath on a mirror. The last thing you see is the blank face of the clock tower. The last thing you hear is Doc’s voice, very small and far away: “Great Scott…”`,
        `In a Hill Valley that never had a working clock, a letter waits in a Western Union vault. Nobody ever comes to collect it.`,
      ],
    },
    {
      id: 'S41',
      title: 'The Stabilizer',
      era: '1985',
      onEnter: { add: { minutes: -79 } },
      cast: ['doc', 'player', 'stabilizer'],
      imagePrompt: `Doc Brown and the player carry the glowing brass Temporal Stabilizer between them up a narrow spiral staircase inside the clock tower, lit by its blue glow, faces tense and determined.`,
      text: [
        `Doc spreads his tools across the workbench in the train’s cab, parked in the frozen square, and sets to work. It takes him seventy-nine minutes to assemble the Temporal Stabilizer. You hold the lamp, pass him tools, and watch the minutes drain off his watch.`,
        `When it’s done, it’s a brass cage about the size of a birdcage: the regulator coiled at its heart, the spare escapement wheel in its socket, and the chrono-cell glowing blue beneath.`,
        `You carry it up the clock tower stairs between you.`,
        { if: { flag: 'delays', is: 0 }, text: `At the top, the clamp’s screen reads 0:21:00. That’s enough time. Just.` },
        { if: { flag: 'delays', is: 1 }, text: `At the top, the clamp’s screen reads 0:01:00. Sixty seconds.` },
        {
          if: { flag: 'delays', gte: 2 },
          text: `You’re three steps from the top when you hear it: a soft, final chime from the clock room. Then the ticking stops.`,
        },
      ],
      choices: [
        { text: `Step into the clock room`, to: 'S42', if: { flag: 'delays', lte: 1 } },
        { text: `Keep climbing`, to: 'E07', if: { flag: 'delays', gte: 2 } },
      ],
    },
    {
      id: 'E07',
      title: 'Frozen Forever',
      era: '1985',
      ending: { kind: 'bad' },
      cast: ['doc', 'player', 'stabilizer', 'clamp'],
      imagePrompt: `The clock room bathed in cold blue stillness: Doc Brown and the player frozen mid-stride at the top of the stairs, holding the brass stabilizer between them, the chrono-clamp’s screen dark. Dust motes hang motionless in the moonlight.`,
      text: [
        `You and Doc reach the clock room together, just in time to watch the clamp’s screen tick from 0:00:01 to 0:00:00.`,
        `There’s no bang and no flash. The green light simply goes out, and the air goes perfectly, permanently still. You feel your bracelet stop humming. You see Doc turn toward you, very slowly, as if through honey, and then not at all.`,
        `Hill Valley stops at 10:04 PM on November 12th, 1985, forever.`,
        {
          if: is('sawExhibit'),
          text: `A hundred years later, in a museum you’ve already visited, a school group files past a new exhibit at the top of the clock tower: a white-haired man and a teenager holding a brass cage between them.`,
          else: `A hundred years later, in a museum called The Frozen Moment, a school group files past an exhibit at the top of the clock tower: a white-haired man and a teenager holding a brass cage between them.`,
        },
        `“Nobody knows who they were,” says the guide, “or what they were trying to do.”`,
      ],
    },
    {
      id: 'S42',
      title: 'Rex',
      era: '1985',
      cast: ['rex', 'doc', 'player', 'stabilizer', 'clamp'],
      imagePrompt: `Showdown in the moonlit clock room among giant iron gears: Rex Tannen in his silver jumpsuit aims a sleek device like a glass flashlight at the glowing brass stabilizer, which Doc Brown is wiring to the chrono-clamp on the clock hands. The player stands between them.`,
      text: [
        {
          if: is('tannenKnows'),
          text: `Someone is already there. Rex Tannen is leaning against the great iron gears in his silver jumpsuit, holding a device like a flashlight made of glass. “You didn’t think I’d let you walk out of my office and then just sit around in 2085 waiting for you, did you?”`,
          else: `The clock room is empty. Doc sets the stabilizer down next to the clamp and starts connecting cables with quick, careful hands. Then the air crackles blue, and Rex Tannen steps out of nowhere: silver jumpsuit, helmet under one arm, and in his other hand a device like a flashlight made of glass. “The clamp called me,” he says. “It doesn’t like being tampered with. Neither do I.”`,
        },
        `He points the glass device at the stabilizer. “Put it down. Slowly.”`,
        {
          if: is('authorityAlerted'),
          text: `Before anyone can move, the air crackles again, three times, four, and suddenly the clock room is very crowded. Four officers in grey uniforms, wearing the hourglass badge of the Temporal Authority, step out of the blue light. The officer from the Hill Valley branch is at the front.`,
        },
        {
          if: is('authorityAlerted'),
          text: `“Rex Tannen,” she says. “You’re under arrest for two unregistered temporal jumps, one of them just now.”`,
        },
      ],
      choices: [
        { text: `Stand back and let them work`, to: 'S44', if: is('authorityAlerted') },
        { text: `Hand over the stabilizer`, to: 'E08', if: not(is('authorityAlerted')) },
        { text: `Keep him talking while Doc finishes the job`, to: 'S43', if: not(is('authorityAlerted')) },
      ],
    },
    {
      id: 'E08',
      title: 'Tannen Time',
      era: '1985',
      ending: { kind: 'bad' },
      cast: ['rex'],
      imagePrompt: `A gaudy futuristic theme park at night built around a historic clock tower, glowing with holographic banners of a smug man’s grinning face. Crowds of tourists stream through the gates; a giant brochure-style billboard shows a frozen teenager and a white-haired man as star attractions.`,
      text: [
        `You set the stabilizer down and slide it across the floor to him. Doc says your name once, quietly.`,
        `Rex picks it up, turns it over, and drops it out of the open maintenance hatch in the clock face. You watch it fall out of your field, slow down, and stop, hanging in the air twenty feet below the window, frozen like everything else.`,
        `“Thank you,” he says, and points the glass flashlight at the two of you.`,
        `The Frozen Moment opens its new wing that spring. It is the most popular exhibit in the history of Tannen Temporal Tours. Rex opens a second attraction the year after, then a third, and then a Tannen Temporal Tours theme park where the old high school used to be.`,
        `You’re in all the brochures.`,
      ],
    },
    {
      id: 'S43',
      title: 'Stalling',
      era: '1985',
      cast: ['rex', 'doc', 'stabilizer', 'clamp'],
      imagePrompt: `In the clock room, Rex Tannen gestures grandly mid-boast, not noticing that behind him Doc Brown has just made the final connection: the brass stabilizer blazes with brilliant blue-white light, its clock wheel spinning, and the chrono-clamp’s green screen flickers out.`,
      text: [
        `“Why a clock tower?” you ask. Your voice comes out higher than you’d like. “Why not freeze somewhere bigger?”`,
        `Rex actually looks pleased to be asked. Villains usually are. “Because this one’s special. Lightning hit this tower in 1955 at 10:04 exactly, and that left a scar in time right here: a weak point. On the thirtieth anniversary, to the minute, it’s at its weakest. One little clamp, and the whole town locks up like a—”`,
        `Behind him, Doc makes the last connection.`,
        `The stabilizer lights up like a lighthouse. The escapement wheel spins, the chrono-cell blazes blue, and a clean, bright tick rings through the clock room, the first honest tick this clock has made in thirty years.`,
        `The clamp’s green screen flickers and goes dark. With a small, embarrassed click, it drops off the hands.`,
        `Rex stares at it. Then he stabs at his wrist device and vanishes in a crack of blue light.`,
        `Through the clock face, you see the minute hand of the Hill Valley clock tower move to 10:05.`,
      ],
      choices: [
        { text: `Continue`, to: 'E09', if: { flag: 'delays', is: 0 } },
        { text: `Continue`, to: 'E11', if: { flag: 'delays', is: 1 } },
      ],
    },
    {
      id: 'S44',
      title: 'Arrest',
      era: '1985',
      cast: ['rex', 'doc', 'stabilizer'],
      imagePrompt: `In the clock room, grey-uniformed Temporal Authority officers cuff a sputtering Rex Tannen in glowing blue handcuffs while Doc Brown connects the final cable; the brass stabilizer blazes with blue-white light and the chrono-clamp falls from the clock hands into an officer’s evidence bag.`,
      text: [
        `Rex backs toward the clock face with his glass flashlight raised, but there are four officers and only one of him. The flashlight goes into an evidence bag. Rex goes into handcuffs that glow faintly blue.`,
        `“You can’t prove anything,” he says.`,
        `“We have your jump log,” the officer says. “We have a clamp with your company’s name stamped on it. And we have two witnesses.” She nods at you and Doc. “Carry on, Doctor.”`,
        `Doc makes the last connection. The stabilizer lights up like a lighthouse. The escapement wheel spins, the chrono-cell blazes blue, and a clean, bright tick rings through the clock room, the first honest tick this clock has made in thirty years. The clamp’s screen goes dark, and it drops off the hands with a small, embarrassed click. One of the officers catches it and bags that too.`,
        `The officers vanish in four flashes of blue, taking Rex with them.`,
        `Through the clock face, you see the minute hand of the Hill Valley clock tower move to 10:05.`,
      ],
      choices: [{ text: `Continue`, to: 'S45' }],
    },
    {
      id: 'S45',
      title: '10:05 PM',
      era: '1985',
      time: 'NOV 12 1985 10:05 PM',
      cast: ['doc', 'player'],
      imagePrompt: `Doc Brown and the player sit exhausted but smiling on the courthouse steps at night, Doc reading an old yellowed letter. Behind them the town has come back to life: a couple walking, a newspaper blowing down the street, the clock tower glowing overhead.`,
      text: [
        `Outside, Hill Valley starts again as if nothing had happened. Red finishes his snore. The couple finish their step. The newspaper blows away down the street. A car honks. Nobody in town will ever know that, for them, the last six hours took no time at all.`,
        `You and Doc sit on the courthouse steps, exhausted. The letter is still in your pocket, creased and soft. You take it out and hand it to him.`,
        `Doc reads it again, the way he did at the start, and this time he smiles.`,
        `“I understand it now,” he says. “I have to write this. I’ll write it in 1885, when I get home, and give it to Western Union with very specific instructions.” He taps the P.S. “And I mustn’t forget this bit.”`,
      ],
      choices: [
        { text: `Continue`, to: 'E10', if: { flag: 'delays', is: 0 } },
        { text: `Continue`, to: 'E11', if: { flag: 'delays', is: 1 } },
      ],
    },
    {
      id: 'E09',
      title: 'Time Keeper',
      era: '1985',
      time: 'NOV 12 1985 10:05 PM',
      ending: { kind: 'good' },
      cast: ['player', 'train'],
      imagePrompt: `The time train lifts off into the night sky above the revived courthouse square, trailing twin tracks of fire. The player watches from the courthouse steps, a set of old iron keys in hand, the clock tower ticking above.`,
      text: [
        `You and Doc carry the stabilizer back down the tower stairs and out into the square just as Hill Valley starts again, as if nothing had happened. Red finishes his snore. The couple finish their step. Nobody will ever know that, for them, the last six hours took no time at all.`,
        `Rex Tannen is still out there somewhere, a hundred years from now, with a grudge and a time machine. Doc doesn’t seem worried. “Let him try,” he says. “This tower has a keeper now.”`,
        `He means you. On Monday, the Preservation Society receives an anonymous donation, large enough to restore the clock tower, with one condition: the young volunteer with the clipboard gets the keys.`,
        `Before he leaves, Doc reads your letter one last time. “I’ll write it in 1885,” he says, “and leave it with Western Union.” He taps the P.S. “Including this bit.”`,
        `The train lifts into the night, turns once over the square, and vanishes in three flashes of light and a pair of fiery tracks that burn on the air for a moment.`,
        `Above you, the clock tower ticks.`,
      ],
    },
    {
      id: 'E10',
      title: 'Right on Time',
      era: '1985',
      ending: { kind: 'good', best: true },
      cast: ['doc', 'player'],
      imagePrompt: `Daytime on the courthouse steps: the player, clipboard under one arm, looks up at the restored, gleaming clock tower, its hands moving. In the foreground Doc Brown’s hand extends toward the player for a handshake. Warm, triumphant light.`,
      text: [
        `Doc stands up, brushes off his coat, and looks at you for a long moment.`,
        `“You know,” he says, “a man who travels in time could use a good assistant. Someone steady. Someone who reads the postscript.” He holds out his hand. “Not every day. You have school. But when the circuits light up, I’d like you there.”`,
        `You shake it.`,
        `A hundred years from now, there will be no museum called the Frozen Moment. There will be no Frozen Moment at all. Rex Tannen’s trial is short.`,
        `On Monday morning, the Preservation Society finds an envelope under its door. Inside is enough money to restore the clock tower completely, and a note in looping handwriting asking that the young volunteer with the clipboard be given the keys.`,
        `A week later you’re back on the courthouse steps, with a clipboard and no flyers left to hand out. Above you, for the first time in thirty years, the clock tower is ticking. At 10:04 that night, it doesn’t stop.`,
      ],
    },
    {
      id: 'E11',
      title: 'The Missing Minute',
      era: '1985',
      time: 'NOV 12 1985 10:05 PM',
      ending: { kind: 'good' },
      cast: ['player'],
      imagePrompt: `A year later, night in the courthouse square: the player stands alone looking up at the ticking clock tower, holding up a wristwatch that shows a time one minute ahead of the tower clock. Town life bustles softly around them.`,
      text: [
        {
          if: not(is('authorityAlerted')),
          text: `You and Doc carry the stabilizer back down the tower stairs and out into the square just as Hill Valley starts again, as if nothing had happened. Red finishes his snore. The couple finish their step. Rex Tannen is still out there somewhere, a hundred years from now, but Doc doesn’t seem worried. Before he leaves, he reads your letter one last time. “I’ll write it in 1885,” he says, and taps the P.S. “Including this bit.”`,
        },
        `There’s just one thing. When the clamp let go, it kept hold of one last minute, the minute that was still on its screen when the stabilizer fired, and it took that minute with it.`,
        `From that night on, every clock in Hill Valley runs exactly sixty seconds slow: watches, ovens, VCRs, church bells. You can set them right and they drift back. Nobody can explain it. The Hill Valley Telegraph runs a series of articles about it.`,
        `“It’s harmless,” Doc says, turning his watch over in his hand. “Mostly harmless. Just a little reminder.”`,
        `Every November 12th, you go down to the square and look up at the clock tower. It always shows the wrong time by exactly one minute, and it always keeps ticking.`,
      ],
    },
  ],
};

export default story;
